/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "custom.h"
#include "nav.h"

uint8_t uart_data_receive[18];
uint8_t uart_data_send[24];

int set_temp = 180;
int set_hour = 0;
int set_min  = 30;

void custom_init()
{
    /* Add your codes here */


    nav_init();
}
