/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void bottom_bbq_menu_probe_create(ui_manager_t *ui)
{
    bottom_bbq_menu_probe_t *scr = bottom_bbq_menu_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_17
    scr->image_17 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_17, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_17, 50, 50);
    lv_img_set_angle(scr->image_17, 0);
    lv_obj_set_style_img_opa(scr->image_17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_17, 24, 118);

    // Init scr->image_18
    scr->image_18 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_18, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_18, 50, 50);
    lv_img_set_angle(scr->image_18, 0);
    lv_obj_set_style_img_opa(scr->image_18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_18, 645, 118);

    // Init scr->label_46
    scr->label_46 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_46, "温度");
    lv_label_set_long_mode(scr->label_46, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_46, 300, 137);
    lv_obj_set_size(scr->label_46, 64, 32);

    // Set style of scr->label_46
    lv_obj_set_style_text_font(scr->label_46, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_46, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 252, 249);
    lv_obj_set_size(scr->temp, 120, 72);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_48
    scr->label_48 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_48, "℃");
    lv_label_set_long_mode(scr->label_48, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_48, 372, 281);
    lv_obj_set_size(scr->label_48, 38, 32);

    // Set style of scr->label_48
    lv_obj_set_style_text_font(scr->label_48, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_48, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_49
    scr->label_49 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_49, "探针温度");
    lv_label_set_long_mode(scr->label_49, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_49, 891, 137);
    lv_obj_set_size(scr->label_49, 125, 32);

    // Set style of scr->label_49
    lv_obj_set_style_text_font(scr->label_49, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_49, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_50
    scr->label_50 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_50, "底部烧烤");
    lv_label_set_long_mode(scr->label_50, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_50, 24, 25);
    lv_obj_set_size(scr->label_50, 144, 32);

    // Set style of scr->label_50
    lv_obj_set_style_text_font(scr->label_50, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_50, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_51
    scr->label_51 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_51, "下一步");
    lv_label_set_long_mode(scr->label_51, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_51, 996, 39);
    lv_obj_set_size(scr->label_51, 117, 32);

    // Set style of scr->label_51
    lv_obj_set_style_text_font(scr->label_51, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_51, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->templine3
    scr->templine3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine3, LVGL_IMAGE_PATH(underline.png));
    lv_img_set_pivot(scr->templine3, 50, 50);
    lv_img_set_angle(scr->templine3, 0);
    lv_obj_set_style_img_opa(scr->templine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine3, 252, 328);
    lv_obj_add_flag(scr->templine3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->templine2
    scr->templine2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine2, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->templine2, 50, 50);
    lv_img_set_angle(scr->templine2, 0);
    lv_obj_set_style_img_opa(scr->templine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine2, 289, 328);
    lv_obj_add_flag(scr->templine2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->probetemp
    scr->probetemp = lv_label_create(scr->obj);
    lv_label_set_text(scr->probetemp, "80");
    lv_label_set_long_mode(scr->probetemp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->probetemp, 853, 249);
    lv_obj_set_size(scr->probetemp, 120, 72);

    // Set style of scr->probetemp
    lv_obj_set_style_text_font(scr->probetemp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->probetemp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->probetemp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->probetemp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_53
    scr->label_53 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_53, "℃");
    lv_label_set_long_mode(scr->label_53, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_53, 973, 281);
    lv_obj_set_size(scr->label_53, 38, 32);

    // Set style of scr->label_53
    lv_obj_set_style_text_font(scr->label_53, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_53, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->probetempline
    scr->probetempline = lv_img_create(scr->obj);
    lv_img_set_src(scr->probetempline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->probetempline, 50, 50);
    lv_img_set_angle(scr->probetempline, 0);
    lv_obj_set_style_img_opa(scr->probetempline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->probetempline, 891, 328);
    lv_obj_add_flag(scr->probetempline, LV_OBJ_FLAG_HIDDEN);


}


