/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void bottom_bbq_cooking_probe_create(ui_manager_t *ui)
{
    bottom_bbq_cooking_probe_t *scr = bottom_bbq_cooking_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 底部烧烤 | 180℃ | 80℃");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "36℃");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 919, 156);
    lv_obj_set_size(scr->temp, 134, 60);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->stop
    scr->stop = lv_btn_create(scr->obj);
    lv_obj_t *stop_label = lv_label_create(scr->stop);
    lv_label_set_text(stop_label, "暂 停");
    lv_obj_align(stop_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->stop, 959, 295);
    lv_obj_set_size(scr->stop, 129, 83);

    // Set style of scr->stop
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->stop, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_23
    scr->image_23 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_23, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_23, 50, 50);
    lv_img_set_angle(scr->image_23, 0);
    lv_obj_set_style_img_opa(scr->image_23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_23, 115, 320);

    // Init scr->bar_5
    scr->bar_5 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_5, 0, 0);
    lv_bar_set_value(scr->bar_5, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_5, 122, 326);
    lv_obj_set_size(scr->bar_5, 637, 20);

    // Set style of scr->bar_5
    lv_obj_set_style_bg_color(scr->bar_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_5, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_24
    scr->image_24 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_24, LVGL_IMAGE_PATH(dwbbqicon.png));
    lv_img_set_pivot(scr->image_24, 50, 50);
    lv_img_set_angle(scr->image_24, 0);
    lv_obj_set_style_img_opa(scr->image_24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_24, 115, 161);

    // Init scr->label_67
    scr->label_67 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_67, "烹饪中...");
    lv_label_set_long_mode(scr->label_67, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_67, 273, 157);
    lv_obj_set_size(scr->label_67, 235, 60);

    // Set style of scr->label_67
    lv_obj_set_style_text_font(scr->label_67, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_67, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_25
    scr->image_25 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_25, LVGL_IMAGE_PATH(probeicon.png));
    lv_img_set_pivot(scr->image_25, 50, 50);
    lv_img_set_angle(scr->image_25, 0);
    lv_obj_set_style_img_opa(scr->image_25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_25, 1068, 180);


}


