/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void bottom_bbq_stop_back_probe_create(ui_manager_t *ui)
{
    bottom_bbq_stop_back_probe_t *scr = bottom_bbq_stop_back_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(scr->obj, lv_color_hex(0x550000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 底部烧烤 | 180℃ | 80℃");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_29
    scr->image_29 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_29, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_29, 50, 50);
    lv_img_set_angle(scr->image_29, 0);
    lv_obj_set_style_img_opa(scr->image_29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_29, 115, 320);

    // Init scr->bar_7
    scr->bar_7 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_7, 0, 0);
    lv_bar_set_value(scr->bar_7, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_7, 122, 326);
    lv_obj_set_size(scr->bar_7, 637, 20);

    // Set style of scr->bar_7
    lv_obj_set_style_bg_color(scr->bar_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_7, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_30
    scr->image_30 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_30, LVGL_IMAGE_PATH(dwbbqicon.png));
    lv_img_set_pivot(scr->image_30, 50, 50);
    lv_img_set_angle(scr->image_30, 0);
    lv_obj_set_style_img_opa(scr->image_30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_30, 115, 161);

    // Init scr->label_72
    scr->label_72 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_72, "暂停中...");
    lv_label_set_long_mode(scr->label_72, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_72, 273, 157);
    lv_obj_set_size(scr->label_72, 235, 60);

    // Set style of scr->label_72
    lv_obj_set_style_text_font(scr->label_72, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_72, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 0, 0);
    lv_obj_set_size(scr->container_2, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_73
    scr->label_73 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_73, "是否结束当前任务");
    lv_label_set_long_mode(scr->label_73, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_73, 895, 160);
    lv_obj_set_size(scr->label_73, 252, 36);

    // Set style of scr->label_73
    lv_obj_set_style_text_font(scr->label_73, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_73, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_73, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_74
    scr->label_74 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_74, "回到主页");
    lv_label_set_long_mode(scr->label_74, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_74, 895, 198);
    lv_obj_set_size(scr->label_74, 252, 36);

    // Set style of scr->label_74
    lv_obj_set_style_text_font(scr->label_74, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_74, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_74, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 定");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


