/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void bread6menu_create(ui_manager_t *ui)
{
    bread6menu_t *scr = bread6menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_11
    scr->label_11 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_11, "面包");
    lv_label_set_long_mode(scr->label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_11, 24, 24);
    lv_obj_set_size(scr->label_11, 144, 32);

    // Set style of scr->label_11
    lv_obj_set_style_text_font(scr->label_11, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_11, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->breadroll
    scr->breadroll = lv_btn_create(scr->obj);
    lv_obj_t *breadroll_label = lv_label_create(scr->breadroll);
    lv_label_set_text(breadroll_label, "面包卷");
    lv_obj_align(breadroll_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->breadroll, 5, 65);
    lv_obj_set_size(scr->breadroll, 340, 406);

    // Set style of scr->breadroll
    lv_obj_set_style_bg_opa(scr->breadroll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->breadroll, LVGL_IMAGE_PATH(div4bg30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->breadroll, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->breadroll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->breadroll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->breadroll, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->breadroll, LVGL_IMAGE_PATH(div4bg80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->wheat_bread
    scr->wheat_bread = lv_btn_create(scr->obj);
    lv_obj_t *wheat_bread_label = lv_label_create(scr->wheat_bread);
    lv_label_set_text(wheat_bread_label, "全麦面包");
    lv_obj_align(wheat_bread_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->wheat_bread, 315, 65);
    lv_obj_set_size(scr->wheat_bread, 340, 406);

    // Set style of scr->wheat_bread
    lv_obj_set_style_bg_opa(scr->wheat_bread, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->wheat_bread, LVGL_IMAGE_PATH(div4bg30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->wheat_bread, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->wheat_bread, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->wheat_bread, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->wheat_bread, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->wheat_bread, LVGL_IMAGE_PATH(div4bg80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->toast
    scr->toast = lv_btn_create(scr->obj);
    lv_obj_t *toast_label = lv_label_create(scr->toast);
    lv_label_set_text(toast_label, "土司");
    lv_obj_align(toast_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->toast, 625, 65);
    lv_obj_set_size(scr->toast, 340, 406);

    // Set style of scr->toast
    lv_obj_set_style_bg_opa(scr->toast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->toast, LVGL_IMAGE_PATH(div4bg30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->toast, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->toast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->toast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->toast, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->toast, LVGL_IMAGE_PATH(div4bg80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->croissant
    scr->croissant = lv_btn_create(scr->obj);
    lv_obj_t *croissant_label = lv_label_create(scr->croissant);
    lv_label_set_text(croissant_label, "可颂");
    lv_obj_align(croissant_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->croissant, 936, 65);
    lv_obj_set_size(scr->croissant, 340, 406);

    // Set style of scr->croissant
    lv_obj_set_style_bg_opa(scr->croissant, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->croissant, LVGL_IMAGE_PATH(div4bg30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->croissant, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->croissant, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->croissant, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->croissant, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->croissant, LVGL_IMAGE_PATH(div4bg80.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


