/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void chip_set_create(ui_manager_t *ui)
{
    chip_set_t *scr = chip_set_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_812
    scr->label_812 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_812, "炸薯条");
    lv_label_set_long_mode(scr->label_812, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_812, 24, 25);
    lv_obj_set_size(scr->label_812, 144, 32);

    // Set style of scr->label_812
    lv_obj_set_style_text_font(scr->label_812, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_812, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_813
    scr->label_813 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_813, "温");
    lv_label_set_long_mode(scr->label_813, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_813, 165, 157);
    lv_obj_set_size(scr->label_813, 26, 32);

    // Set style of scr->label_813
    lv_obj_set_style_text_font(scr->label_813, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_813, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_814
    scr->label_814 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_814, "度：");
    lv_label_set_long_mode(scr->label_814, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_814, 252, 157);
    lv_obj_set_size(scr->label_814, 64, 32);

    // Set style of scr->label_814
    lv_obj_set_style_text_font(scr->label_814, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_814, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_814, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_815
    scr->label_815 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_815, "烹饪时间：");
    lv_label_set_long_mode(scr->label_815, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_815, 141, 270);
    lv_obj_set_size(scr->label_815, 175, 32);

    // Set style of scr->label_815
    lv_obj_set_style_text_font(scr->label_815, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_815, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_815, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "01");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 307, 254);
    lv_obj_set_size(scr->hour, 62, 53);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "20");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 395, 254);
    lv_obj_set_size(scr->min, 58, 53);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_818
    scr->label_818 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_818, "时");
    lv_label_set_long_mode(scr->label_818, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_818, 368, 270);
    lv_obj_set_size(scr->label_818, 30, 32);

    // Set style of scr->label_818
    lv_obj_set_style_text_font(scr->label_818, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_818, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_818, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_819
    scr->label_819 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_819, "分钟");
    lv_label_set_long_mode(scr->label_819, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_819, 448, 269);
    lv_obj_set_size(scr->label_819, 64, 32);

    // Set style of scr->label_819
    lv_obj_set_style_text_font(scr->label_819, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_819, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_819, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_375
    scr->image_375 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_375, LVGL_IMAGE_PATH(place_1.png));
    lv_img_set_pivot(scr->image_375, 50, 50);
    lv_img_set_angle(scr->image_375, 0);
    lv_obj_set_style_img_opa(scr->image_375, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_375, 164, 376);

    // Init scr->label_820
    scr->label_820 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_820, "烤架位置 3");
    lv_label_set_long_mode(scr->label_820, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_820, 232, 385);
    lv_obj_set_size(scr->label_820, 148, 32);

    // Set style of scr->label_820
    lv_obj_set_style_text_font(scr->label_820, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_820, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_820, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 983, 22);
    lv_obj_set_size(scr->sure, 135, 71);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_821
    scr->label_821 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_821, "延");
    lv_label_set_long_mode(scr->label_821, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_821, 840, 154);
    lv_obj_set_size(scr->label_821, 26, 32);

    // Set style of scr->label_821
    lv_obj_set_style_text_font(scr->label_821, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_821, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_822
    scr->label_822 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_822, "迟");
    lv_label_set_long_mode(scr->label_822, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_822, 930, 154);
    lv_obj_set_size(scr->label_822, 26, 32);

    // Set style of scr->label_822
    lv_obj_set_style_text_font(scr->label_822, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_822, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_823
    scr->label_823 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_823, "自动保温");
    lv_label_set_long_mode(scr->label_823, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_823, 831, 270);
    lv_obj_set_size(scr->label_823, 130, 32);

    // Set style of scr->label_823
    lv_obj_set_style_text_font(scr->label_823, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_823, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_823, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->offdelay
    scr->offdelay = lv_btn_create(scr->obj);
    lv_obj_t *offdelay_label = lv_label_create(scr->offdelay);
    lv_label_set_text(offdelay_label, "");
    lv_obj_align(offdelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offdelay, 983, 144);
    lv_obj_set_size(scr->offdelay, 135, 53);

    // Set style of scr->offdelay
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offdelay, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->offcontain
    scr->offcontain = lv_btn_create(scr->obj);
    lv_obj_t *offcontain_label = lv_label_create(scr->offcontain);
    lv_label_set_text(offcontain_label, "");
    lv_obj_align(offcontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offcontain, 983, 260);
    lv_obj_set_size(scr->offcontain, 135, 53);

    // Set style of scr->offcontain
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offcontain, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "230");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 315, 141);
    lv_obj_set_size(scr->temp, 83, 53);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_825
    scr->label_825 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_825, "确 定");
    lv_label_set_long_mode(scr->label_825, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_825, 1010, 39);
    lv_obj_set_size(scr->label_825, 85, 36);

    // Set style of scr->label_825
    lv_obj_set_style_text_font(scr->label_825, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_825, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ondelay
    scr->ondelay = lv_btn_create(scr->obj);
    lv_obj_t *ondelay_label = lv_label_create(scr->ondelay);
    lv_label_set_text(ondelay_label, "");
    lv_obj_align(ondelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->ondelay, 983, 144);
    lv_obj_set_size(scr->ondelay, 135, 53);
    lv_obj_add_flag(scr->ondelay, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->ondelay
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->ondelay, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->oncontain
    scr->oncontain = lv_btn_create(scr->obj);
    lv_obj_t *oncontain_label = lv_label_create(scr->oncontain);
    lv_label_set_text(oncontain_label, "");
    lv_obj_align(oncontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->oncontain, 983, 260);
    lv_obj_set_size(scr->oncontain, 135, 53);
    lv_obj_add_flag(scr->oncontain, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->oncontain
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->oncontain, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 396, 157);
    lv_obj_set_size(scr->icon3, 32, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 369, 157);
    lv_obj_set_size(scr->icon2, 32, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


}


