/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void chip_setting_create(ui_manager_t *ui)
{
    chip_setting_t *scr = chip_setting_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timelabel
    scr->timelabel = lv_label_create(scr->obj);
    lv_label_set_text(scr->timelabel, "00:19:59");
    lv_label_set_long_mode(scr->timelabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->timelabel, 907, 157);
    lv_obj_set_size(scr->timelabel, 235, 60);

    // Set style of scr->timelabel
    lv_obj_set_style_text_font(scr->timelabel, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->timelabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_37
    scr->container_37 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_37, 0, 0);
    lv_obj_set_size(scr->container_37, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_37, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_37
    lv_obj_set_style_bg_color(scr->container_37, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_37, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_378
    scr->image_378 = lv_img_create(scr->container_37);
    lv_img_set_src(scr->image_378, LVGL_IMAGE_PATH(settingbk.png));
    lv_img_set_pivot(scr->image_378, 50, 50);
    lv_img_set_angle(scr->image_378, 0);
    lv_obj_set_style_img_opa(scr->image_378, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_378, 115, 115);

    // Init scr->label_832
    scr->label_832 = lv_label_create(scr->container_37);
    lv_label_set_text(scr->label_832, "烹饪时间");
    lv_label_set_long_mode(scr->label_832, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_832, 373, 136);
    lv_obj_set_size(scr->label_832, 135, 30);

    // Set style of scr->label_832
    lv_obj_set_style_text_font(scr->label_832, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_832, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_832, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->container_37);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 266, 212);
    lv_obj_set_size(scr->hour, 102, 46);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_834
    scr->label_834 = lv_label_create(scr->container_37);
    lv_label_set_text(scr->label_834, "时");
    lv_label_set_long_mode(scr->label_834, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_834, 340, 228);
    lv_obj_set_size(scr->label_834, 37, 30);

    // Set style of scr->label_834
    lv_obj_set_style_text_font(scr->label_834, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_834, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_834, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->container_37);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 291, 269);

    // Init scr->min
    scr->min = lv_label_create(scr->container_37);
    lv_label_set_text(scr->min, "00");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 483, 212);
    lv_obj_set_size(scr->min, 102, 46);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_836
    scr->label_836 = lv_label_create(scr->container_37);
    lv_label_set_text(scr->label_836, "分");
    lv_label_set_long_mode(scr->label_836, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_836, 558, 229);
    lv_obj_set_size(scr->label_836, 37, 30);

    // Set style of scr->label_836
    lv_obj_set_style_text_font(scr->label_836, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_836, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_836, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->minline
    scr->minline = lv_img_create(scr->container_37);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 508, 269);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 认");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


