/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void cook_menu_tz_create(ui_manager_t *ui)
{
    cook_menu_tz_t *scr = cook_menu_tz_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(scr->obj, lv_color_hex(0x672a22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(scr->obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hot_bbq_button
    scr->hot_bbq_button = lv_btn_create(scr->obj);
    lv_obj_t *hot_bbq_button_label = lv_label_create(scr->hot_bbq_button);
    lv_label_set_text(hot_bbq_button_label, "");
    lv_obj_align(hot_bbq_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->hot_bbq_button, 421, 60);
    lv_obj_set_size(scr->hot_bbq_button, 439, 417);

    // Set style of scr->hot_bbq_button
    lv_obj_set_style_bg_opa(scr->hot_bbq_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->hot_bbq_button, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->hot_bbq_button, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->hot_bbq_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->hot_bbq_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->hot_bbq_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->hot_bbq_button, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->updown_button
    scr->updown_button = lv_btn_create(scr->obj);
    lv_obj_t *updown_button_label = lv_label_create(scr->updown_button);
    lv_label_set_text(updown_button_label, "");
    lv_obj_align(updown_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->updown_button, 7, 60);
    lv_obj_set_size(scr->updown_button, 439, 417);

    // Set style of scr->updown_button
    lv_obj_set_style_bg_opa(scr->updown_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->updown_button, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->updown_button, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->updown_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->updown_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->updown_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->updown_button, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->bottom_button
    scr->bottom_button = lv_btn_create(scr->obj);
    lv_obj_t *bottom_button_label = lv_label_create(scr->bottom_button);
    lv_label_set_text(bottom_button_label, "");
    lv_obj_align(bottom_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->bottom_button, 835, 60);
    lv_obj_set_size(scr->bottom_button, 439, 417);

    // Set style of scr->bottom_button
    lv_obj_set_style_bg_opa(scr->bottom_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->bottom_button, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->bottom_button, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bottom_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->bottom_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bottom_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->bottom_button, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->major_img
    scr->major_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->major_img, LVGL_IMAGE_PATH(pengrentzimg.png));
    lv_img_set_pivot(scr->major_img, 50, 50);
    lv_img_set_angle(scr->major_img, 0);
    lv_obj_set_style_img_opa(scr->major_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->major_img, 175, 188);

    // Init scr->cook_label
    scr->cook_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->cook_label, "烹饪功能");
    lv_label_set_long_mode(scr->cook_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cook_label, 24, 24);
    lv_obj_set_size(scr->cook_label, 96, 22);

    // Set style of scr->cook_label
    lv_obj_set_style_text_font(scr->cook_label, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cook_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->cook_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label
    scr->time_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->time_label, "12:00");
    lv_label_set_long_mode(scr->time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label, 1196, 24);
    lv_obj_set_size(scr->time_label, 60, 22);

    // Set style of scr->time_label
    lv_obj_set_style_text_font(scr->time_label, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->time_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->updown_label
    scr->updown_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->updown_label, "上下烧烤");
    lv_label_set_long_mode(scr->updown_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->updown_label, 153, 291);
    lv_obj_set_size(scr->updown_label, 147, 28);

    // Set style of scr->updown_label
    lv_obj_set_style_text_font(scr->updown_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->updown_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->updown_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hot_label
    scr->hot_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->hot_label, "热风烧烤");
    lv_label_set_long_mode(scr->hot_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hot_label, 567, 291);
    lv_obj_set_size(scr->hot_label, 147, 28);

    // Set style of scr->hot_label
    lv_obj_set_style_text_font(scr->hot_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hot_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hot_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bottom_label
    scr->bottom_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->bottom_label, "底部烧烤");
    lv_label_set_long_mode(scr->bottom_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->bottom_label, 981, 291);
    lv_obj_set_size(scr->bottom_label, 147, 30);

    // Set style of scr->bottom_label
    lv_obj_set_style_text_font(scr->bottom_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->bottom_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->bottom_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


