/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void heatcontain_stop_back_create(ui_manager_t *ui)
{
    heatcontain_stop_back_t *scr = heatcontain_stop_back_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(scr->obj, lv_color_hex(0x550000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_277
    scr->image_277 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_277, LVGL_IMAGE_PATH(heatcontainicon.png));
    lv_img_set_pivot(scr->image_277, 50, 50);
    lv_img_set_angle(scr->image_277, 0);
    lv_obj_set_style_img_opa(scr->image_277, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_277, 90, 161);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 保温 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_278
    scr->image_278 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_278, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_278, 50, 50);
    lv_img_set_angle(scr->image_278, 0);
    lv_obj_set_style_img_opa(scr->image_278, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_278, 115, 320);

    // Init scr->bar_46
    scr->bar_46 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_46, 0, 0);
    lv_bar_set_value(scr->bar_46, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_46, 122, 326);
    lv_obj_set_size(scr->bar_46, 637, 20);

    // Set style of scr->bar_46
    lv_obj_set_style_bg_color(scr->bar_46, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_46, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_627
    scr->label_627 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_627, "暂停中...");
    lv_label_set_long_mode(scr->label_627, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_627, 273, 157);
    lv_obj_set_size(scr->label_627, 235, 60);

    // Set style of scr->label_627
    lv_obj_set_style_text_font(scr->label_627, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_627, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->container_28
    scr->container_28 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_28, 0, 0);
    lv_obj_set_size(scr->container_28, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_28, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_28
    lv_obj_set_style_bg_color(scr->container_28, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_28, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_628
    scr->label_628 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_628, "是否结束当前任务");
    lv_label_set_long_mode(scr->label_628, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_628, 895, 160);
    lv_obj_set_size(scr->label_628, 252, 36);

    // Set style of scr->label_628
    lv_obj_set_style_text_font(scr->label_628, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_628, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_628, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_629
    scr->label_629 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_629, "回到主页");
    lv_label_set_long_mode(scr->label_629, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_629, 895, 198);
    lv_obj_set_size(scr->label_629, 252, 36);

    // Set style of scr->label_629
    lv_obj_set_style_text_font(scr->label_629, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_629, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_629, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 定");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


