/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hot_bbq_set_probe_create(ui_manager_t *ui)
{
    hot_bbq_set_probe_t *scr = hot_bbq_set_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_9, "热风烧烤");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 24, 25);
    lv_obj_set_size(scr->label_9, 144, 32);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_10, "温");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 165, 155);
    lv_obj_set_size(scr->label_10, 26, 32);

    // Set style of scr->label_10
    lv_obj_set_style_text_font(scr->label_10, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_11
    scr->label_11 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_11, "度：");
    lv_label_set_long_mode(scr->label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_11, 252, 155);
    lv_obj_set_size(scr->label_11, 64, 32);

    // Set style of scr->label_11
    lv_obj_set_style_text_font(scr->label_11, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_11, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_12, "探针温度：");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 141, 270);
    lv_obj_set_size(scr->label_12, 175, 32);

    // Set style of scr->label_12
    lv_obj_set_style_text_font(scr->label_12, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_12, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(place_1.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_style_img_opa(scr->image_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_6, 164, 376);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_13, "烤架位置 3");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 232, 385);
    lv_obj_set_size(scr->label_13, 148, 32);

    // Set style of scr->label_13
    lv_obj_set_style_text_font(scr->label_13, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_13, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 983, 22);
    lv_obj_set_size(scr->sure, 135, 71);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_20
    scr->label_20 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_20, "确 定");
    lv_label_set_long_mode(scr->label_20, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_20, 1010, 39);
    lv_obj_set_size(scr->label_20, 85, 36);

    // Set style of scr->label_20
    lv_obj_set_style_text_font(scr->label_20, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_20, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->probetemp
    scr->probetemp = lv_label_create(scr->obj);
    lv_label_set_text(scr->probetemp, "80");
    lv_label_set_long_mode(scr->probetemp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->probetemp, 315, 254);
    lv_obj_set_size(scr->probetemp, 83, 53);

    // Set style of scr->probetemp
    lv_obj_set_style_text_font(scr->probetemp, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->probetemp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->probetemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_28
    scr->label_28 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_28, "℃");
    lv_label_set_long_mode(scr->label_28, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_28, 369, 270);
    lv_obj_set_size(scr->label_28, 32, 30);

    // Set style of scr->label_28
    lv_obj_set_style_text_font(scr->label_28, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_28, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_28, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "200");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 315, 141);
    lv_obj_set_size(scr->temp, 83, 53);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 369, 157);
    lv_obj_set_size(scr->icon2, 32, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 396, 157);
    lv_obj_set_size(scr->icon3, 32, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


}


