/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hot_bbq_menu_probe_create(ui_manager_t *ui)
{
    hot_bbq_menu_probe_t *scr = hot_bbq_menu_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 24, 118);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 645, 118);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "温度");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 300, 137);
    lv_obj_set_size(scr->label_1, 64, 32);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 252, 249);
    lv_obj_set_size(scr->temp, 120, 72);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "℃");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 372, 281);
    lv_obj_set_size(scr->label_3, 38, 32);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_4, "探针温度");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 891, 137);
    lv_obj_set_size(scr->label_4, 125, 32);

    // Set style of scr->label_4
    lv_obj_set_style_text_font(scr->label_4, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_5, "热风烧烤");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 24, 24);
    lv_obj_set_size(scr->label_5, 144, 32);

    // Set style of scr->label_5
    lv_obj_set_style_text_font(scr->label_5, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_6, "下一步");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 996, 39);
    lv_obj_set_size(scr->label_6, 117, 32);

    // Set style of scr->label_6
    lv_obj_set_style_text_font(scr->label_6, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->templine3
    scr->templine3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine3, LVGL_IMAGE_PATH(underline.png));
    lv_img_set_pivot(scr->templine3, 50, 50);
    lv_img_set_angle(scr->templine3, 0);
    lv_obj_set_style_img_opa(scr->templine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine3, 252, 328);
    lv_obj_add_flag(scr->templine3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->templine2
    scr->templine2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine2, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->templine2, 50, 50);
    lv_img_set_angle(scr->templine2, 0);
    lv_obj_set_style_img_opa(scr->templine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine2, 289, 328);
    lv_obj_add_flag(scr->templine2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->probetemp
    scr->probetemp = lv_label_create(scr->obj);
    lv_label_set_text(scr->probetemp, "80");
    lv_label_set_long_mode(scr->probetemp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->probetemp, 853, 249);
    lv_obj_set_size(scr->probetemp, 120, 72);

    // Set style of scr->probetemp
    lv_obj_set_style_text_font(scr->probetemp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->probetemp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->probetemp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->probetemp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_8, "℃");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 973, 281);
    lv_obj_set_size(scr->label_8, 38, 32);

    // Set style of scr->label_8
    lv_obj_set_style_text_font(scr->label_8, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->probetempline
    scr->probetempline = lv_img_create(scr->obj);
    lv_img_set_src(scr->probetempline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->probetempline, 50, 50);
    lv_img_set_angle(scr->probetempline, 0);
    lv_obj_set_style_img_opa(scr->probetempline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->probetempline, 891, 328);
    lv_obj_add_flag(scr->probetempline, LV_OBJ_FLAG_HIDDEN);


}


