/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hotcleanhigh_stop_back_create(ui_manager_t *ui)
{
    hotcleanhigh_stop_back_t *scr = hotcleanhigh_stop_back_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 热解自清洁 | 2小时 |");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_style_img_opa(scr->image_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_5, 115, 320);

    // Init scr->bar_3
    scr->bar_3 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_3, 0, 0);
    lv_bar_set_value(scr->bar_3, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_3, 122, 326);
    lv_obj_set_size(scr->bar_3, 637, 20);

    // Set style of scr->bar_3
    lv_obj_set_style_bg_color(scr->bar_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_3, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(hotcleanhighicon.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_style_img_opa(scr->image_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_6, 115, 161);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_16, "暂停中...");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 273, 157);
    lv_obj_set_size(scr->label_16, 235, 60);

    // Set style of scr->label_16
    lv_obj_set_style_text_font(scr->label_16, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_5
    scr->button_5 = lv_btn_create(scr->obj);
    lv_obj_t *button_5_label = lv_label_create(scr->button_5);
    lv_label_set_text(button_5_label, "");
    lv_obj_align(button_5_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_5, 609, 170);
    lv_obj_set_size(scr->button_5, 50, 43);

    // Set style of scr->button_5
    lv_obj_set_style_bg_opa(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_5, LVGL_IMAGE_PATH(lockicon.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_5, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->container_3
    scr->container_3 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_3, 0, 0);
    lv_obj_set_size(scr->container_3, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_3
    lv_obj_set_style_bg_color(scr->container_3, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_3, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 定");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_17
    scr->label_17 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_17, "是否结束当前任务");
    lv_label_set_long_mode(scr->label_17, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_17, 895, 160);
    lv_obj_set_size(scr->label_17, 252, 36);

    // Set style of scr->label_17
    lv_obj_set_style_text_font(scr->label_17, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_17, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_18
    scr->label_18 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_18, "回到主页");
    lv_label_set_long_mode(scr->label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_18, 895, 198);
    lv_obj_set_size(scr->label_18, 252, 36);

    // Set style of scr->label_18
    lv_obj_set_style_text_font(scr->label_18, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_18, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


