/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hotcleanmiddle_stop_create(ui_manager_t *ui)
{
    hotcleanmiddle_stop_t *scr = hotcleanmiddle_stop_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 热解自清洁 | 1小时40分钟 |");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timelabel
    scr->timelabel = lv_label_create(scr->obj);
    lv_label_set_text(scr->timelabel, "00:19:59");
    lv_label_set_long_mode(scr->timelabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->timelabel, 907, 157);
    lv_obj_set_size(scr->timelabel, 235, 60);

    // Set style of scr->timelabel
    lv_obj_set_style_text_font(scr->timelabel, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->timelabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->start
    scr->start = lv_btn_create(scr->obj);
    lv_obj_t *start_label = lv_label_create(scr->start);
    lv_label_set_text(start_label, "开 始");
    lv_obj_align(start_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->start, 959, 295);
    lv_obj_set_size(scr->start, 129, 83);

    // Set style of scr->start
    lv_obj_set_style_bg_opa(scr->start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->start, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->start, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->start, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->start, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_7
    scr->image_7 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_7, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_7, 50, 50);
    lv_img_set_angle(scr->image_7, 0);
    lv_obj_set_style_img_opa(scr->image_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_7, 115, 320);

    // Init scr->bar_3
    scr->bar_3 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_3, 0, 0);
    lv_bar_set_value(scr->bar_3, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_3, 122, 326);
    lv_obj_set_size(scr->bar_3, 637, 20);

    // Set style of scr->bar_3
    lv_obj_set_style_bg_color(scr->bar_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_3, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(hotcleanmiddleicon.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_style_img_opa(scr->image_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_8, 115, 161);

    // Init scr->label_11
    scr->label_11 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_11, "暂停中...");
    lv_label_set_long_mode(scr->label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_11, 273, 157);
    lv_obj_set_size(scr->label_11, 235, 60);

    // Set style of scr->label_11
    lv_obj_set_style_text_font(scr->label_11, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_11, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_5
    scr->button_5 = lv_btn_create(scr->obj);
    lv_obj_t *button_5_label = lv_label_create(scr->button_5);
    lv_label_set_text(button_5_label, "");
    lv_obj_align(button_5_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_5, 609, 170);
    lv_obj_set_size(scr->button_5, 50, 43);

    // Set style of scr->button_5
    lv_obj_set_style_bg_opa(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_5, LVGL_IMAGE_PATH(lockicon.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_5, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);


}


