/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hotcleanhigh_cooling_create(ui_manager_t *ui)
{
    hotcleanhigh_cooling_t *scr = hotcleanhigh_cooling_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_20
    scr->image_20 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_20, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_20, 50, 50);
    lv_img_set_angle(scr->image_20, 0);
    lv_obj_set_style_img_opa(scr->image_20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_20, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 热解自清洁 | 2小时");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_8
    scr->bar_8 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_8, 0, 0);
    lv_bar_set_value(scr->bar_8, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_8, 122, 326);
    lv_obj_set_size(scr->bar_8, 637, 20);

    // Set style of scr->bar_8
    lv_obj_set_style_bg_color(scr->bar_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_8, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_21
    scr->image_21 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_21, LVGL_IMAGE_PATH(hotcleanhighicon.png));
    lv_img_set_pivot(scr->image_21, 50, 50);
    lv_img_set_angle(scr->image_21, 0);
    lv_obj_set_style_img_opa(scr->image_21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_21, 115, 161);

    // Init scr->label_26
    scr->label_26 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_26, "冷却中...");
    lv_label_set_long_mode(scr->label_26, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_26, 273, 157);
    lv_obj_set_size(scr->label_26, 235, 60);

    // Set style of scr->label_26
    lv_obj_set_style_text_font(scr->label_26, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_26, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_22
    scr->image_22 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_22, LVGL_IMAGE_PATH(hotcleantips.png));
    lv_img_set_pivot(scr->image_22, 50, 50);
    lv_img_set_angle(scr->image_22, 0);
    lv_obj_set_style_img_opa(scr->image_22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_22, 902, 160);

    // Init scr->button_12
    scr->button_12 = lv_btn_create(scr->obj);
    lv_obj_t *button_12_label = lv_label_create(scr->button_12);
    lv_label_set_text(button_12_label, "");
    lv_obj_align(button_12_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_12, 609, 170);
    lv_obj_set_size(scr->button_12, 50, 43);

    // Set style of scr->button_12
    lv_obj_set_style_bg_opa(scr->button_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_12, LVGL_IMAGE_PATH(lockicon.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_12, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_12, 0, LV_PART_MAIN | LV_STATE_FOCUSED);


}


