/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void hotwind_bbq_menu_create(ui_manager_t *ui)
{
    hotwind_bbq_menu_t *scr = hotwind_bbq_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_98
    scr->image_98 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_98, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_98, 50, 50);
    lv_img_set_angle(scr->image_98, 0);
    lv_obj_set_style_img_opa(scr->image_98, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_98, 24, 118);

    // Init scr->image_99
    scr->image_99 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_99, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_99, 50, 50);
    lv_img_set_angle(scr->image_99, 0);
    lv_obj_set_style_img_opa(scr->image_99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_99, 645, 118);

    // Init scr->label_205
    scr->label_205 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_205, "温度");
    lv_label_set_long_mode(scr->label_205, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_205, 300, 137);
    lv_obj_set_size(scr->label_205, 64, 32);

    // Set style of scr->label_205
    lv_obj_set_style_text_font(scr->label_205, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_205, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 252, 249);
    lv_obj_set_size(scr->temp, 120, 72);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_207
    scr->label_207 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_207, "℃");
    lv_label_set_long_mode(scr->label_207, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_207, 372, 281);
    lv_obj_set_size(scr->label_207, 38, 32);

    // Set style of scr->label_207
    lv_obj_set_style_text_font(scr->label_207, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_207, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_208
    scr->label_208 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_208, "烹饪时间");
    lv_label_set_long_mode(scr->label_208, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_208, 891, 137);
    lv_obj_set_size(scr->label_208, 125, 32);

    // Set style of scr->label_208
    lv_obj_set_style_text_font(scr->label_208, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_208, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 793, 248);
    lv_obj_set_size(scr->hour, 84, 72);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_210
    scr->label_210 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_210, "时");
    lv_label_set_long_mode(scr->label_210, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_210, 872, 280);
    lv_obj_set_size(scr->label_210, 38, 32);

    // Set style of scr->label_210
    lv_obj_set_style_text_font(scr->label_210, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_210, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_211
    scr->label_211 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_211, "分");
    lv_label_set_long_mode(scr->label_211, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_211, 1075, 281);
    lv_obj_set_size(scr->label_211, 38, 32);

    // Set style of scr->label_211
    lv_obj_set_style_text_font(scr->label_211, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_211, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "30");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 995, 248);
    lv_obj_set_size(scr->min, 84, 72);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_213
    scr->label_213 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_213, "热风");
    lv_label_set_long_mode(scr->label_213, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_213, 24, 24);
    lv_obj_set_size(scr->label_213, 144, 32);

    // Set style of scr->label_213
    lv_obj_set_style_text_font(scr->label_213, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_213, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_214
    scr->label_214 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_214, "下一步");
    lv_label_set_long_mode(scr->label_214, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_214, 996, 39);
    lv_obj_set_size(scr->label_214, 117, 32);

    // Set style of scr->label_214
    lv_obj_set_style_text_font(scr->label_214, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_214, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->templine3
    scr->templine3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine3, LVGL_IMAGE_PATH(underline.png));
    lv_img_set_pivot(scr->templine3, 50, 50);
    lv_img_set_angle(scr->templine3, 0);
    lv_obj_set_style_img_opa(scr->templine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine3, 252, 328);
    lv_obj_add_flag(scr->templine3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->templine2
    scr->templine2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine2, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->templine2, 50, 50);
    lv_img_set_angle(scr->templine2, 0);
    lv_obj_set_style_img_opa(scr->templine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine2, 289, 328);
    lv_obj_add_flag(scr->templine2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->obj);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 790, 328);
    lv_obj_add_flag(scr->hourline, LV_OBJ_FLAG_HIDDEN);

    // Init scr->minline
    scr->minline = lv_img_create(scr->obj);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 993, 328);
    lv_obj_add_flag(scr->minline, LV_OBJ_FLAG_HIDDEN);


}


