/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void lasagna_complete_create(ui_manager_t *ui)
{
    lasagna_complete_t *scr = lasagna_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_321
    scr->image_321 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_321, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_321, 50, 50);
    lv_img_set_angle(scr->image_321, 0);
    lv_obj_set_style_img_opa(scr->image_321, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_321, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 千层面 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_51
    scr->bar_51 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_51, 0, 0);
    lv_bar_set_value(scr->bar_51, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_51, 122, 326);
    lv_obj_set_size(scr->bar_51, 637, 20);

    // Set style of scr->bar_51
    lv_obj_set_style_bg_color(scr->bar_51, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_51, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_681
    scr->label_681 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_681, "已完成");
    lv_label_set_long_mode(scr->label_681, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_681, 273, 157);
    lv_obj_set_size(scr->label_681, 235, 60);

    // Set style of scr->label_681
    lv_obj_set_style_text_font(scr->label_681, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_681, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_323
    scr->image_323 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_323, LVGL_IMAGE_PATH(lasagnaicon.png));
    lv_img_set_pivot(scr->image_323, 50, 50);
    lv_img_set_angle(scr->image_323, 0);
    lv_obj_set_style_img_opa(scr->image_323, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_323, 115, 161);

    // Init scr->image_12
    scr->image_12 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_12, LVGL_IMAGE_PATH(tips.png));
    lv_img_set_pivot(scr->image_12, 50, 50);
    lv_img_set_angle(scr->image_12, 0);
    lv_obj_set_style_img_opa(scr->image_12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_12, 902, 160);


}


