/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void menu_complete_create(ui_manager_t *ui)
{
    menu_complete_t *scr = menu_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_132
    scr->image_132 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_132, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_132, 50, 50);
    lv_img_set_angle(scr->image_132, 0);
    lv_obj_set_style_img_opa(scr->image_132, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_132, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 菜单 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_19
    scr->bar_19 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_19, 0, 0);
    lv_bar_set_value(scr->bar_19, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_19, 122, 326);
    lv_obj_set_size(scr->bar_19, 637, 20);

    // Set style of scr->bar_19
    lv_obj_set_style_bg_color(scr->bar_19, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_19, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_288
    scr->label_288 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_288, "已完成");
    lv_label_set_long_mode(scr->label_288, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_288, 273, 157);
    lv_obj_set_size(scr->label_288, 235, 60);

    // Set style of scr->label_288
    lv_obj_set_style_text_font(scr->label_288, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_288, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_133
    scr->image_133 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_133, LVGL_IMAGE_PATH(hotcare.png));
    lv_img_set_pivot(scr->image_133, 50, 50);
    lv_img_set_angle(scr->image_133, 0);
    lv_obj_set_style_img_opa(scr->image_133, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_133, 845, 160);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_134
    scr->image_134 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_134, LVGL_IMAGE_PATH(menuicon.png));
    lv_img_set_pivot(scr->image_134, 50, 50);
    lv_img_set_angle(scr->image_134, 0);
    lv_obj_set_style_img_opa(scr->image_134, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_134, 115, 161);


}


