/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void pizza_stop_back_create(ui_manager_t *ui)
{
    pizza_stop_back_t *scr = pizza_stop_back_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(scr->obj, lv_color_hex(0x550000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_109
    scr->image_109 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_109, LVGL_IMAGE_PATH(pizzaicon.png));
    lv_img_set_pivot(scr->image_109, 50, 50);
    lv_img_set_angle(scr->image_109, 0);
    lv_obj_set_style_img_opa(scr->image_109, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_109, 115, 161);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 披萨 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_110
    scr->image_110 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_110, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_110, 50, 50);
    lv_img_set_angle(scr->image_110, 0);
    lv_obj_set_style_img_opa(scr->image_110, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_110, 115, 320);

    // Init scr->bar_14
    scr->bar_14 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_14, 0, 0);
    lv_bar_set_value(scr->bar_14, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_14, 122, 326);
    lv_obj_set_size(scr->bar_14, 637, 20);

    // Set style of scr->bar_14
    lv_obj_set_style_bg_color(scr->bar_14, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_14, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_236
    scr->label_236 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_236, "暂停中...");
    lv_label_set_long_mode(scr->label_236, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_236, 273, 157);
    lv_obj_set_size(scr->label_236, 235, 60);

    // Set style of scr->label_236
    lv_obj_set_style_text_font(scr->label_236, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_236, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->container_12
    scr->container_12 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_12, 0, 0);
    lv_obj_set_size(scr->container_12, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_12, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_12
    lv_obj_set_style_bg_color(scr->container_12, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_12, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_237
    scr->label_237 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_237, "是否结束当前任务");
    lv_label_set_long_mode(scr->label_237, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_237, 895, 160);
    lv_obj_set_size(scr->label_237, 252, 36);

    // Set style of scr->label_237
    lv_obj_set_style_text_font(scr->label_237, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_237, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_237, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_238
    scr->label_238 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_238, "回到主页");
    lv_label_set_long_mode(scr->label_238, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_238, 895, 198);
    lv_obj_set_size(scr->label_238, 252, 36);

    // Set style of scr->label_238
    lv_obj_set_style_text_font(scr->label_238, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_238, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_238, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 定");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


