/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void pizza_2_cooking_create(ui_manager_t *ui)
{
    pizza_2_cooking_t *scr = pizza_2_cooking_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 披萨 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timelabel
    scr->timelabel = lv_label_create(scr->obj);
    lv_label_set_text(scr->timelabel, "00:19:59");
    lv_label_set_long_mode(scr->timelabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->timelabel, 907, 157);
    lv_obj_set_size(scr->timelabel, 235, 60);

    // Set style of scr->timelabel
    lv_obj_set_style_text_font(scr->timelabel, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->timelabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->stop
    scr->stop = lv_btn_create(scr->obj);
    lv_obj_t *stop_label = lv_label_create(scr->stop);
    lv_label_set_text(stop_label, "暂 停");
    lv_obj_align(stop_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->stop, 959, 295);
    lv_obj_set_size(scr->stop, 129, 83);

    // Set style of scr->stop
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->stop, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_163
    scr->image_163 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_163, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_163, 50, 50);
    lv_img_set_angle(scr->image_163, 0);
    lv_obj_set_style_img_opa(scr->image_163, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_163, 115, 320);

    // Init scr->bar_24
    scr->bar_24 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_24, 0, 0);
    lv_bar_set_value(scr->bar_24, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_24, 122, 326);
    lv_obj_set_size(scr->bar_24, 637, 20);

    // Set style of scr->bar_24
    lv_obj_set_style_bg_color(scr->bar_24, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_24, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_367
    scr->label_367 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_367, "烹饪中...");
    lv_label_set_long_mode(scr->label_367, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_367, 273, 157);
    lv_obj_set_size(scr->label_367, 235, 60);

    // Set style of scr->label_367
    lv_obj_set_style_text_font(scr->label_367, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_367, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_164
    scr->image_164 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_164, LVGL_IMAGE_PATH(pizza2icon.png));
    lv_img_set_pivot(scr->image_164, 50, 50);
    lv_img_set_angle(scr->image_164, 0);
    lv_obj_set_style_img_opa(scr->image_164, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_164, 115, 161);


}


