/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void pizza_set_create(ui_manager_t *ui)
{
    pizza_set_t *scr = pizza_set_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_203
    scr->label_203 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_203, "披萨");
    lv_label_set_long_mode(scr->label_203, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_203, 24, 24);
    lv_obj_set_size(scr->label_203, 144, 32);

    // Set style of scr->label_203
    lv_obj_set_style_text_font(scr->label_203, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_203, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_204
    scr->label_204 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_204, "温");
    lv_label_set_long_mode(scr->label_204, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_204, 165, 157);
    lv_obj_set_size(scr->label_204, 26, 32);

    // Set style of scr->label_204
    lv_obj_set_style_text_font(scr->label_204, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_204, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_205
    scr->label_205 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_205, "度：");
    lv_label_set_long_mode(scr->label_205, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_205, 252, 157);
    lv_obj_set_size(scr->label_205, 64, 32);

    // Set style of scr->label_205
    lv_obj_set_style_text_font(scr->label_205, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_205, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_205, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_206
    scr->label_206 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_206, "烹饪时间：");
    lv_label_set_long_mode(scr->label_206, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_206, 141, 270);
    lv_obj_set_size(scr->label_206, 175, 32);

    // Set style of scr->label_206
    lv_obj_set_style_text_font(scr->label_206, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_206, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_206, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "01");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 307, 254);
    lv_obj_set_size(scr->hour, 62, 53);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "20");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 395, 254);
    lv_obj_set_size(scr->min, 58, 53);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_209
    scr->label_209 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_209, "时");
    lv_label_set_long_mode(scr->label_209, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_209, 368, 270);
    lv_obj_set_size(scr->label_209, 30, 32);

    // Set style of scr->label_209
    lv_obj_set_style_text_font(scr->label_209, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_209, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_209, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_210
    scr->label_210 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_210, "分钟");
    lv_label_set_long_mode(scr->label_210, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_210, 448, 269);
    lv_obj_set_size(scr->label_210, 64, 32);

    // Set style of scr->label_210
    lv_obj_set_style_text_font(scr->label_210, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_210, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_210, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_99
    scr->image_99 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_99, LVGL_IMAGE_PATH(place_1.png));
    lv_img_set_pivot(scr->image_99, 50, 50);
    lv_img_set_angle(scr->image_99, 0);
    lv_obj_set_style_img_opa(scr->image_99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_99, 164, 376);

    // Init scr->label_211
    scr->label_211 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_211, "烤架位置 3");
    lv_label_set_long_mode(scr->label_211, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_211, 232, 385);
    lv_obj_set_size(scr->label_211, 148, 32);

    // Set style of scr->label_211
    lv_obj_set_style_text_font(scr->label_211, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_211, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_211, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 983, 22);
    lv_obj_set_size(scr->sure, 135, 71);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_212
    scr->label_212 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_212, "延");
    lv_label_set_long_mode(scr->label_212, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_212, 840, 154);
    lv_obj_set_size(scr->label_212, 26, 32);

    // Set style of scr->label_212
    lv_obj_set_style_text_font(scr->label_212, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_212, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_213
    scr->label_213 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_213, "迟");
    lv_label_set_long_mode(scr->label_213, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_213, 930, 154);
    lv_obj_set_size(scr->label_213, 26, 32);

    // Set style of scr->label_213
    lv_obj_set_style_text_font(scr->label_213, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_213, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_214
    scr->label_214 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_214, "自动保温");
    lv_label_set_long_mode(scr->label_214, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_214, 831, 270);
    lv_obj_set_size(scr->label_214, 130, 32);

    // Set style of scr->label_214
    lv_obj_set_style_text_font(scr->label_214, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_214, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_214, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->offdelay
    scr->offdelay = lv_btn_create(scr->obj);
    lv_obj_t *offdelay_label = lv_label_create(scr->offdelay);
    lv_label_set_text(offdelay_label, "");
    lv_obj_align(offdelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offdelay, 983, 144);
    lv_obj_set_size(scr->offdelay, 135, 53);

    // Set style of scr->offdelay
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offdelay, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->offcontain
    scr->offcontain = lv_btn_create(scr->obj);
    lv_obj_t *offcontain_label = lv_label_create(scr->offcontain);
    lv_label_set_text(offcontain_label, "");
    lv_obj_align(offcontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offcontain, 983, 260);
    lv_obj_set_size(scr->offcontain, 135, 53);

    // Set style of scr->offcontain
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offcontain, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "210");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 315, 141);
    lv_obj_set_size(scr->temp, 83, 53);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_216
    scr->label_216 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_216, "确 定");
    lv_label_set_long_mode(scr->label_216, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_216, 1010, 39);
    lv_obj_set_size(scr->label_216, 85, 36);

    // Set style of scr->label_216
    lv_obj_set_style_text_font(scr->label_216, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_216, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ondelay
    scr->ondelay = lv_btn_create(scr->obj);
    lv_obj_t *ondelay_label = lv_label_create(scr->ondelay);
    lv_label_set_text(ondelay_label, "");
    lv_obj_align(ondelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->ondelay, 983, 144);
    lv_obj_set_size(scr->ondelay, 135, 53);
    lv_obj_add_flag(scr->ondelay, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->ondelay
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->ondelay, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->oncontain
    scr->oncontain = lv_btn_create(scr->obj);
    lv_obj_t *oncontain_label = lv_label_create(scr->oncontain);
    lv_label_set_text(oncontain_label, "");
    lv_obj_align(oncontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->oncontain, 983, 260);
    lv_obj_set_size(scr->oncontain, 135, 53);
    lv_obj_add_flag(scr->oncontain, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->oncontain
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->oncontain, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 396, 157);
    lv_obj_set_size(scr->icon3, 32, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 369, 157);
    lv_obj_set_size(scr->icon2, 32, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


}


