/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void pizza_2_complete_create(ui_manager_t *ui)
{
    pizza_2_complete_t *scr = pizza_2_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_174
    scr->image_174 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_174, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_174, 50, 50);
    lv_img_set_angle(scr->image_174, 0);
    lv_obj_set_style_img_opa(scr->image_174, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_174, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 披萨 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_27
    scr->bar_27 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_27, 0, 0);
    lv_bar_set_value(scr->bar_27, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_27, 122, 326);
    lv_obj_set_size(scr->bar_27, 637, 20);

    // Set style of scr->bar_27
    lv_obj_set_style_bg_color(scr->bar_27, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_27, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_386
    scr->label_386 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_386, "已完成");
    lv_label_set_long_mode(scr->label_386, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_386, 273, 157);
    lv_obj_set_size(scr->label_386, 235, 60);

    // Set style of scr->label_386
    lv_obj_set_style_text_font(scr->label_386, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_386, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_175
    scr->image_175 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_175, LVGL_IMAGE_PATH(hotcare.png));
    lv_img_set_pivot(scr->image_175, 50, 50);
    lv_img_set_angle(scr->image_175, 0);
    lv_obj_set_style_img_opa(scr->image_175, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_175, 845, 160);

    // Init scr->little
    scr->little = lv_btn_create(scr->obj);
    lv_obj_t *little_label = lv_label_create(scr->little);
    lv_label_set_text(little_label, "");
    lv_obj_align(little_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little, 609, 170);
    lv_obj_set_size(scr->little, 50, 43);

    // Set style of scr->little
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_176
    scr->image_176 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_176, LVGL_IMAGE_PATH(pizza2icon.png));
    lv_img_set_pivot(scr->image_176, 50, 50);
    lv_img_set_angle(scr->image_176, 0);
    lv_obj_set_style_img_opa(scr->image_176, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_176, 140, 161);


}


