/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void preheatstop_create(ui_manager_t *ui)
{
    preheatstop_t *scr = preheatstop_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_75
    scr->label_75 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_75, "| 预热 |");
    lv_label_set_long_mode(scr->label_75, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_75, 274, 232);
    lv_obj_set_size(scr->label_75, 490, 39);

    // Set style of scr->label_75
    lv_obj_set_style_text_font(scr->label_75, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_75, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180℃");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 940, 157);
    lv_obj_set_size(scr->temp, 159, 60);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_10
    scr->button_10 = lv_btn_create(scr->obj);
    lv_obj_t *button_10_label = lv_label_create(scr->button_10);
    lv_label_set_text(button_10_label, "开 始");
    lv_obj_align(button_10_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_10, 959, 295);
    lv_obj_set_size(scr->button_10, 129, 83);

    // Set style of scr->button_10
    lv_obj_set_style_bg_opa(scr->button_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_10, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_10, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_10, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_10, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_41
    scr->image_41 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_41, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_41, 50, 50);
    lv_img_set_angle(scr->image_41, 0);
    lv_obj_set_style_img_opa(scr->image_41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_41, 115, 320);

    // Init scr->bar_2
    scr->bar_2 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_2, 0, 0);
    lv_bar_set_value(scr->bar_2, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_2, 122, 326);
    lv_obj_set_size(scr->bar_2, 637, 20);

    // Set style of scr->bar_2
    lv_obj_set_style_bg_color(scr->bar_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_2, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_77
    scr->label_77 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_77, "预热中...");
    lv_label_set_long_mode(scr->label_77, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_77, 273, 157);
    lv_obj_set_size(scr->label_77, 235, 60);

    // Set style of scr->label_77
    lv_obj_set_style_text_font(scr->label_77, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_77, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_42
    scr->image_42 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_42, LVGL_IMAGE_PATH(preheaticon.png));
    lv_img_set_pivot(scr->image_42, 50, 50);
    lv_img_set_angle(scr->image_42, 0);
    lv_obj_set_style_img_opa(scr->image_42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_42, 115, 161);

    // Init scr->label_78
    scr->label_78 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_78, "预热");
    lv_label_set_long_mode(scr->label_78, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_78, 24, 24);
    lv_obj_set_size(scr->label_78, 144, 32);

    // Set style of scr->label_78
    lv_obj_set_style_text_font(scr->label_78, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_78, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);


}


