/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void risingpage_create(ui_manager_t *ui)
{
    risingpage_t *scr = risingpage_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(div1bg.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_style_img_opa(scr->image_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_6, 24, 119);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_16, "是否有发酵阶段");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 406, 259);
    lv_obj_set_size(scr->label_16, 469, 51);

    // Set style of scr->label_16
    lv_obj_set_style_text_font(scr->label_16, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->yes
    scr->yes = lv_btn_create(scr->obj);
    lv_obj_t *yes_label = lv_label_create(scr->yes);
    lv_label_set_text(yes_label, "是");
    lv_obj_align(yes_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->yes, 885, 247);
    lv_obj_set_size(scr->yes, 129, 83);

    // Set style of scr->yes
    lv_obj_set_style_bg_opa(scr->yes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->yes, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->yes, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->yes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->yes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->yes, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->yes, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->no
    scr->no = lv_btn_create(scr->obj);
    lv_obj_t *no_label = lv_label_create(scr->no);
    lv_label_set_text(no_label, "否");
    lv_obj_align(no_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->no, 268, 247);
    lv_obj_set_size(scr->no, 129, 83);

    // Set style of scr->no
    lv_obj_set_style_bg_opa(scr->no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->no, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->no, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->no, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->no, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->no, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_17
    scr->label_17 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_17, "面包卷");
    lv_label_set_long_mode(scr->label_17, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_17, 24, 24);
    lv_obj_set_size(scr->label_17, 144, 32);

    // Set style of scr->label_17
    lv_obj_set_style_text_font(scr->label_17, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_17, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);


}


