/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void rising_set_create(ui_manager_t *ui)
{
    rising_set_t *scr = rising_set_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_495
    scr->label_495 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_495, "发酵");
    lv_label_set_long_mode(scr->label_495, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_495, 24, 25);
    lv_obj_set_size(scr->label_495, 144, 32);

    // Set style of scr->label_495
    lv_obj_set_style_text_font(scr->label_495, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_495, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_496
    scr->label_496 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_496, "温");
    lv_label_set_long_mode(scr->label_496, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_496, 165, 157);
    lv_obj_set_size(scr->label_496, 26, 32);

    // Set style of scr->label_496
    lv_obj_set_style_text_font(scr->label_496, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_496, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_497
    scr->label_497 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_497, "度：");
    lv_label_set_long_mode(scr->label_497, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_497, 252, 157);
    lv_obj_set_size(scr->label_497, 64, 32);

    // Set style of scr->label_497
    lv_obj_set_style_text_font(scr->label_497, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_497, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_497, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_498
    scr->label_498 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_498, "烹饪时间：");
    lv_label_set_long_mode(scr->label_498, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_498, 141, 270);
    lv_obj_set_size(scr->label_498, 175, 32);

    // Set style of scr->label_498
    lv_obj_set_style_text_font(scr->label_498, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_498, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_498, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "01");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 307, 254);
    lv_obj_set_size(scr->hour, 62, 53);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "20");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 395, 254);
    lv_obj_set_size(scr->min, 58, 53);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_501
    scr->label_501 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_501, "时");
    lv_label_set_long_mode(scr->label_501, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_501, 368, 270);
    lv_obj_set_size(scr->label_501, 30, 32);

    // Set style of scr->label_501
    lv_obj_set_style_text_font(scr->label_501, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_501, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_501, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_502
    scr->label_502 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_502, "分钟");
    lv_label_set_long_mode(scr->label_502, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_502, 448, 269);
    lv_obj_set_size(scr->label_502, 64, 32);

    // Set style of scr->label_502
    lv_obj_set_style_text_font(scr->label_502, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_502, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_502, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_225
    scr->image_225 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_225, LVGL_IMAGE_PATH(place_1.png));
    lv_img_set_pivot(scr->image_225, 50, 50);
    lv_img_set_angle(scr->image_225, 0);
    lv_obj_set_style_img_opa(scr->image_225, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_225, 164, 376);

    // Init scr->label_503
    scr->label_503 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_503, "烤架位置 3");
    lv_label_set_long_mode(scr->label_503, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_503, 232, 385);
    lv_obj_set_size(scr->label_503, 148, 32);

    // Set style of scr->label_503
    lv_obj_set_style_text_font(scr->label_503, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_503, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_503, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 983, 22);
    lv_obj_set_size(scr->sure, 135, 71);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_504
    scr->label_504 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_504, "快速预热");
    lv_label_set_long_mode(scr->label_504, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_504, 830, 154);
    lv_obj_set_size(scr->label_504, 130, 32);

    // Set style of scr->label_504
    lv_obj_set_style_text_font(scr->label_504, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_504, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_504, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_505
    scr->label_505 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_505, "延");
    lv_label_set_long_mode(scr->label_505, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_505, 840, 270);
    lv_obj_set_size(scr->label_505, 26, 32);

    // Set style of scr->label_505
    lv_obj_set_style_text_font(scr->label_505, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_505, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_506
    scr->label_506 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_506, "迟");
    lv_label_set_long_mode(scr->label_506, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_506, 930, 270);
    lv_obj_set_size(scr->label_506, 26, 32);

    // Set style of scr->label_506
    lv_obj_set_style_text_font(scr->label_506, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_506, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_507
    scr->label_507 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_507, "自动保温");
    lv_label_set_long_mode(scr->label_507, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_507, 831, 381);
    lv_obj_set_size(scr->label_507, 130, 32);

    // Set style of scr->label_507
    lv_obj_set_style_text_font(scr->label_507, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_507, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_507, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->offpreheat
    scr->offpreheat = lv_btn_create(scr->obj);
    lv_obj_t *offpreheat_label = lv_label_create(scr->offpreheat);
    lv_label_set_text(offpreheat_label, "");
    lv_obj_align(offpreheat_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offpreheat, 983, 144);
    lv_obj_set_size(scr->offpreheat, 135, 53);

    // Set style of scr->offpreheat
    lv_obj_set_style_bg_opa(scr->offpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offpreheat, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offpreheat, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offpreheat, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offpreheat, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->offdelay
    scr->offdelay = lv_btn_create(scr->obj);
    lv_obj_t *offdelay_label = lv_label_create(scr->offdelay);
    lv_label_set_text(offdelay_label, "");
    lv_obj_align(offdelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offdelay, 983, 260);
    lv_obj_set_size(scr->offdelay, 135, 53);

    // Set style of scr->offdelay
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offdelay, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offdelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offdelay, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->offcontain
    scr->offcontain = lv_btn_create(scr->obj);
    lv_obj_t *offcontain_label = lv_label_create(scr->offcontain);
    lv_label_set_text(offcontain_label, "");
    lv_obj_align(offcontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->offcontain, 983, 372);
    lv_obj_set_size(scr->offcontain, 135, 53);

    // Set style of scr->offcontain
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->offcontain, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->offcontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->offcontain, LVGL_IMAGE_PATH(focusoff.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 315, 141);
    lv_obj_set_size(scr->temp, 83, 53);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_509
    scr->label_509 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_509, "确 定");
    lv_label_set_long_mode(scr->label_509, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_509, 1010, 39);
    lv_obj_set_size(scr->label_509, 85, 36);

    // Set style of scr->label_509
    lv_obj_set_style_text_font(scr->label_509, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_509, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->onpreheat
    scr->onpreheat = lv_btn_create(scr->obj);
    lv_obj_t *onpreheat_label = lv_label_create(scr->onpreheat);
    lv_label_set_text(onpreheat_label, "");
    lv_obj_align(onpreheat_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->onpreheat, 983, 144);
    lv_obj_set_size(scr->onpreheat, 135, 53);
    lv_obj_add_flag(scr->onpreheat, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->onpreheat
    lv_obj_set_style_bg_opa(scr->onpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->onpreheat, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->onpreheat, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->onpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->onpreheat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->onpreheat, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->onpreheat, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->ondelay
    scr->ondelay = lv_btn_create(scr->obj);
    lv_obj_t *ondelay_label = lv_label_create(scr->ondelay);
    lv_label_set_text(ondelay_label, "");
    lv_obj_align(ondelay_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->ondelay, 983, 260);
    lv_obj_set_size(scr->ondelay, 135, 53);
    lv_obj_add_flag(scr->ondelay, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->ondelay
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->ondelay, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->ondelay, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->ondelay, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->oncontain
    scr->oncontain = lv_btn_create(scr->obj);
    lv_obj_t *oncontain_label = lv_label_create(scr->oncontain);
    lv_label_set_text(oncontain_label, "");
    lv_obj_align(oncontain_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->oncontain, 983, 372);
    lv_obj_set_size(scr->oncontain, 135, 53);
    lv_obj_add_flag(scr->oncontain, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->oncontain
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->oncontain, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->oncontain, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->oncontain, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 396, 157);
    lv_obj_set_size(scr->icon3, 32, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 369, 157);
    lv_obj_set_size(scr->icon2, 32, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


}


