/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void rising_cooking_create(ui_manager_t *ui)
{
    rising_cooking_t *scr = rising_cooking_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 发酵 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timelabel
    scr->timelabel = lv_label_create(scr->obj);
    lv_label_set_text(scr->timelabel, "00:19:59");
    lv_label_set_long_mode(scr->timelabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->timelabel, 907, 157);
    lv_obj_set_size(scr->timelabel, 235, 60);

    // Set style of scr->timelabel
    lv_obj_set_style_text_font(scr->timelabel, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->timelabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->stop
    scr->stop = lv_btn_create(scr->obj);
    lv_obj_t *stop_label = lv_label_create(scr->stop);
    lv_label_set_text(stop_label, "暂 停");
    lv_obj_align(stop_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->stop, 959, 295);
    lv_obj_set_size(scr->stop, 129, 83);

    // Set style of scr->stop
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->stop, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->stop, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->stop, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_226
    scr->image_226 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_226, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_226, 50, 50);
    lv_img_set_angle(scr->image_226, 0);
    lv_obj_set_style_img_opa(scr->image_226, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_226, 115, 320);

    // Init scr->bar_36
    scr->bar_36 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_36, 0, 0);
    lv_bar_set_value(scr->bar_36, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_36, 122, 326);
    lv_obj_set_size(scr->bar_36, 637, 20);

    // Set style of scr->bar_36
    lv_obj_set_style_bg_color(scr->bar_36, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_36, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_514
    scr->label_514 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_514, "烹饪中...");
    lv_label_set_long_mode(scr->label_514, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_514, 273, 157);
    lv_obj_set_size(scr->label_514, 235, 60);

    // Set style of scr->label_514
    lv_obj_set_style_text_font(scr->label_514, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_514, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->liitle
    scr->liitle = lv_btn_create(scr->obj);
    lv_obj_t *liitle_label = lv_label_create(scr->liitle);
    lv_label_set_text(liitle_label, "");
    lv_obj_align(liitle_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->liitle, 609, 170);
    lv_obj_set_size(scr->liitle, 50, 43);

    // Set style of scr->liitle
    lv_obj_set_style_bg_opa(scr->liitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->liitle, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->liitle, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->liitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->liitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->liitle, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->liitle, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_227
    scr->image_227 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_227, LVGL_IMAGE_PATH(risingicon.png));
    lv_img_set_pivot(scr->image_227, 50, 50);
    lv_img_set_angle(scr->image_227, 0);
    lv_obj_set_style_img_opa(scr->image_227, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_227, 115, 161);


}


