/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void rising_setting_create(ui_manager_t *ui)
{
    rising_setting_t *scr = rising_setting_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timelabel
    scr->timelabel = lv_label_create(scr->obj);
    lv_label_set_text(scr->timelabel, "00:19:59");
    lv_label_set_long_mode(scr->timelabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->timelabel, 907, 157);
    lv_obj_set_size(scr->timelabel, 235, 60);

    // Set style of scr->timelabel
    lv_obj_set_style_text_font(scr->timelabel, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->timelabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_23
    scr->container_23 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_23, 0, 0);
    lv_obj_set_size(scr->container_23, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_23, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_23
    lv_obj_set_style_bg_color(scr->container_23, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_23, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_228
    scr->image_228 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_228, LVGL_IMAGE_PATH(settingbk.png));
    lv_img_set_pivot(scr->image_228, 50, 50);
    lv_img_set_angle(scr->image_228, 0);
    lv_obj_set_style_img_opa(scr->image_228, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_228, 115, 115);

    // Init scr->label_516
    scr->label_516 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_516, "温度");
    lv_label_set_long_mode(scr->label_516, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_516, 242, 136);
    lv_obj_set_size(scr->label_516, 73, 30);

    // Set style of scr->label_516
    lv_obj_set_style_text_font(scr->label_516, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_516, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_516, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_517
    scr->label_517 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_517, "烹饪时间");
    lv_label_set_long_mode(scr->label_517, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_517, 454, 136);
    lv_obj_set_size(scr->label_517, 135, 30);

    // Set style of scr->label_517
    lv_obj_set_style_text_font(scr->label_517, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_517, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_517, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 213, 213);
    lv_obj_set_size(scr->temp, 102, 46);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 300, 229);
    lv_obj_set_size(scr->icon3, 37, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->templine2
    scr->templine2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine2, LVGL_IMAGE_PATH(settingline3_87x4.png));
    lv_img_set_pivot(scr->templine2, 50, 50);
    lv_img_set_angle(scr->templine2, 0);
    lv_obj_set_style_img_opa(scr->templine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine2, 236, 269);

    // Init scr->templine3
    scr->templine3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine3, LVGL_IMAGE_PATH(settingline2.png));
    lv_img_set_pivot(scr->templine3, 50, 50);
    lv_img_set_angle(scr->templine3, 0);
    lv_obj_set_style_img_opa(scr->templine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine3, 223, 269);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 374, 213);
    lv_obj_set_size(scr->hour, 102, 46);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "00");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 537, 213);
    lv_obj_set_size(scr->min, 102, 46);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_522
    scr->label_522 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_522, "时");
    lv_label_set_long_mode(scr->label_522, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_522, 449, 229);
    lv_obj_set_size(scr->label_522, 37, 30);

    // Set style of scr->label_522
    lv_obj_set_style_text_font(scr->label_522, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_522, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_522, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_523
    scr->label_523 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_523, "分");
    lv_label_set_long_mode(scr->label_523, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_523, 612, 229);
    lv_obj_set_size(scr->label_523, 37, 30);

    // Set style of scr->label_523
    lv_obj_set_style_text_font(scr->label_523, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_523, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_523, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->obj);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 398, 269);

    // Init scr->minline
    scr->minline = lv_img_create(scr->obj);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 560, 269);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 288, 229);
    lv_obj_set_size(scr->icon2, 37, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 认");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


