/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void save_bbq_complete_create(ui_manager_t *ui)
{
    save_bbq_complete_t *scr = save_bbq_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_127
    scr->image_127 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_127, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_127, 50, 50);
    lv_img_set_angle(scr->image_127, 0);
    lv_obj_set_style_img_opa(scr->image_127, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_127, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 节能热风 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_25
    scr->bar_25 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_25, 0, 0);
    lv_bar_set_value(scr->bar_25, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_25, 122, 326);
    lv_obj_set_size(scr->bar_25, 637, 20);

    // Set style of scr->bar_25
    lv_obj_set_style_bg_color(scr->bar_25, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_25, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_280
    scr->label_280 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_280, "已完成");
    lv_label_set_long_mode(scr->label_280, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_280, 273, 157);
    lv_obj_set_size(scr->label_280, 235, 60);

    // Set style of scr->label_280
    lv_obj_set_style_text_font(scr->label_280, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_280, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_89
    scr->button_89 = lv_btn_create(scr->obj);
    lv_obj_t *button_89_label = lv_label_create(scr->button_89);
    lv_label_set_text(button_89_label, "");
    lv_obj_align(button_89_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_89, 609, 170);
    lv_obj_set_size(scr->button_89, 50, 43);

    // Set style of scr->button_89
    lv_obj_set_style_bg_opa(scr->button_89, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_89, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_89, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_89, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_89, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_89, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_89, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_129
    scr->image_129 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_129, LVGL_IMAGE_PATH(savewindicon.png));
    lv_img_set_pivot(scr->image_129, 50, 50);
    lv_img_set_angle(scr->image_129, 0);
    lv_obj_set_style_img_opa(scr->image_129, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_129, 115, 161);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(tips.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_style_img_opa(scr->image_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_4, 902, 160);


}


