/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void screen_1_create(ui_manager_t *ui)
{
    screen_1_t *scr = screen_1_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(stepsetbg1.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->roller_1
    scr->roller_1 = lv_roller_create(scr->obj);
    lv_roller_set_options(scr->roller_1, "上下烧烤\n顶部烧烤\n热风烧烤", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_visible_row_count(scr->roller_1, 3);
    lv_obj_set_pos(scr->roller_1, 381, 277);
    lv_obj_set_size(scr->roller_1, 223, 124);

    // Set style of scr->roller_1
    lv_obj_set_style_bg_opa(scr->roller_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_1, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_1, lv_color_hex(0xff5580), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->roller_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_1, &c_taiwanpearl_regular_38, LV_PART_SELECTED | LV_STATE_DEFAULT);

    // Init scr->roller_2
    scr->roller_2 = lv_roller_create(scr->obj);
    lv_roller_set_options(scr->roller_2, "上下烧烤\n顶部烧烤\n热风烧烤", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_visible_row_count(scr->roller_2, 3);
    lv_obj_set_pos(scr->roller_2, 422, 372);
    lv_obj_set_size(scr->roller_2, 130, 49);

    // Set style of scr->roller_2
    lv_obj_set_style_bg_opa(scr->roller_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_2, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_2, lv_color_hex(0x6d615f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->roller_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->roller_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->roller_2, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->roller_2, &c_taiwanpearl_regular_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->roller_2, lv_color_hex(0x6d615f), LV_PART_SELECTED | LV_STATE_DEFAULT);


}


