/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void sixmenutz_create(ui_manager_t *ui)
{
    sixmenutz_t *scr = sixmenutz_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "第六感");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 24, 24);
    lv_obj_set_size(scr->label_7, 97, 25);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chick
    scr->chick = lv_btn_create(scr->obj);
    lv_obj_t *chick_label = lv_label_create(scr->chick);
    lv_label_set_text(chick_label, "");
    lv_obj_align(chick_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->chick, 12, 75);
    lv_obj_set_size(scr->chick, 638, 387);

    // Set style of scr->chick
    lv_obj_set_style_bg_opa(scr->chick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->chick, LVGL_IMAGE_PATH(div230bg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->chick, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->chick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->chick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->chick, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->chick, LVGL_IMAGE_PATH(div280bg.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->meat
    scr->meat = lv_btn_create(scr->obj);
    lv_obj_t *meat_label = lv_label_create(scr->meat);
    lv_label_set_text(meat_label, "");
    lv_obj_align(meat_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->meat, 633, 74);
    lv_obj_set_size(scr->meat, 637, 389);

    // Set style of scr->meat
    lv_obj_set_style_bg_opa(scr->meat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->meat, LVGL_IMAGE_PATH(div230bg.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->meat, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->meat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->meat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->meat, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->meat, LVGL_IMAGE_PATH(div280bg.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(sixtz.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_style_img_opa(scr->image_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_3, 267, 192);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_8, "家禽");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 265, 288);
    lv_obj_set_size(scr->label_8, 131, 32);

    // Set style of scr->label_8
    lv_obj_set_style_text_font(scr->label_8, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_9, "肉");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 886, 288);
    lv_obj_set_size(scr->label_9, 131, 32);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


