/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void sixop3page_create(ui_manager_t *ui)
{
    sixop3page_t *scr = sixop3page_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bt2
    scr->bt2 = lv_btn_create(scr->obj);
    lv_obj_t *bt2_label = lv_label_create(scr->bt2);
    lv_label_set_text(bt2_label, "");
    lv_obj_align(bt2_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->bt2, 421, 60);
    lv_obj_set_size(scr->bt2, 439, 417);

    // Set style of scr->bt2
    lv_obj_set_style_bg_opa(scr->bt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->bt2, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->bt2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->bt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bt2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->bt2, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->bt1
    scr->bt1 = lv_btn_create(scr->obj);
    lv_obj_t *bt1_label = lv_label_create(scr->bt1);
    lv_label_set_text(bt1_label, "");
    lv_obj_align(bt1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->bt1, 7, 60);
    lv_obj_set_size(scr->bt1, 439, 417);

    // Set style of scr->bt1
    lv_obj_set_style_bg_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->bt1, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->bt1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->bt1, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->bt3
    scr->bt3 = lv_btn_create(scr->obj);
    lv_obj_t *bt3_label = lv_label_create(scr->bt3);
    lv_label_set_text(bt3_label, "");
    lv_obj_align(bt3_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->bt3, 835, 60);
    lv_obj_set_size(scr->bt3, 439, 417);

    // Set style of scr->bt3
    lv_obj_set_style_bg_opa(scr->bt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->bt3, LVGL_IMAGE_PATH(div3bk30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->bt3, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->bt3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bt3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->bt3, LVGL_IMAGE_PATH(div3bk80.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->name
    scr->name = lv_label_create(scr->obj);
    lv_label_set_text(scr->name, "菜单");
    lv_label_set_long_mode(scr->name, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->name, 24, 24);
    lv_obj_set_size(scr->name, 58, 22);

    // Set style of scr->name
    lv_obj_set_style_text_font(scr->name, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->name, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->name, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->op1
    scr->op1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->op1, "烹饪功能");
    lv_label_set_long_mode(scr->op1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->op1, 153, 274);
    lv_obj_set_size(scr->op1, 147, 28);

    // Set style of scr->op1
    lv_obj_set_style_text_font(scr->op1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->op1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->op1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->op2
    scr->op2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->op2, "COOK 4");
    lv_label_set_long_mode(scr->op2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->op2, 567, 274);
    lv_obj_set_size(scr->op2, 147, 28);

    // Set style of scr->op2
    lv_obj_set_style_text_font(scr->op2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->op2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->op2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->op3
    scr->op3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->op3, "特殊功能");
    lv_label_set_long_mode(scr->op3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->op3, 981, 274);
    lv_obj_set_size(scr->op3, 147, 30);

    // Set style of scr->op3
    lv_obj_set_style_text_font(scr->op3, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->op3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->op3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->probe1
    scr->probe1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->probe1, LVGL_IMAGE_PATH(probeiconbig.png));
    lv_img_set_pivot(scr->probe1, 50, 50);
    lv_img_set_angle(scr->probe1, 0);
    lv_obj_set_style_img_opa(scr->probe1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->probe1, 192, 213);

    // Init scr->probe2
    scr->probe2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->probe2, LVGL_IMAGE_PATH(probeiconbig.png));
    lv_img_set_pivot(scr->probe2, 50, 50);
    lv_img_set_angle(scr->probe2, 0);
    lv_obj_set_style_img_opa(scr->probe2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->probe2, 606, 213);

    // Init scr->probe3
    scr->probe3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->probe3, LVGL_IMAGE_PATH(probeiconbig.png));
    lv_img_set_pivot(scr->probe3, 50, 50);
    lv_img_set_angle(scr->probe3, 0);
    lv_obj_set_style_img_opa(scr->probe3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->probe3, 1020, 213);


}


