/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void slowcook_complete_probe_create(ui_manager_t *ui)
{
    slowcook_complete_probe_t *scr = slowcook_complete_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_47
    scr->image_47 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_47, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_47, 50, 50);
    lv_img_set_angle(scr->image_47, 0);
    lv_obj_set_style_img_opa(scr->image_47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_47, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 慢煮 | 180℃ | 80℃");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_12
    scr->bar_12 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_12, 0, 0);
    lv_bar_set_value(scr->bar_12, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_12, 122, 326);
    lv_obj_set_size(scr->bar_12, 637, 20);

    // Set style of scr->bar_12
    lv_obj_set_style_bg_color(scr->bar_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_12, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_48
    scr->image_48 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_48, LVGL_IMAGE_PATH(slowcookicon.png));
    lv_img_set_pivot(scr->image_48, 50, 50);
    lv_img_set_angle(scr->image_48, 0);
    lv_obj_set_style_img_opa(scr->image_48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_48, 115, 161);

    // Init scr->label_109
    scr->label_109 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_109, "已完成");
    lv_label_set_long_mode(scr->label_109, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_109, 273, 157);
    lv_obj_set_size(scr->label_109, 235, 60);

    // Set style of scr->label_109
    lv_obj_set_style_text_font(scr->label_109, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_109, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_110
    scr->label_110 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_110, "高温防烫");
    lv_label_set_long_mode(scr->label_110, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_110, 896, 161);
    lv_obj_set_size(scr->label_110, 252, 36);

    // Set style of scr->label_110
    lv_obj_set_style_text_font(scr->label_110, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_110, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_110, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_111
    scr->label_111 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_111, "请缓慢打开门体！");
    lv_label_set_long_mode(scr->label_111, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_111, 896, 197);
    lv_obj_set_size(scr->label_111, 252, 36);

    // Set style of scr->label_111
    lv_obj_set_style_text_font(scr->label_111, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_111, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_111, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


