/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void strudel_menu_create(ui_manager_t *ui)
{
    strudel_menu_t *scr = strudel_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_324
    scr->image_324 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_324, LVGL_IMAGE_PATH(div1bg.png));
    lv_img_set_pivot(scr->image_324, 50, 50);
    lv_img_set_angle(scr->image_324, 0);
    lv_obj_set_style_img_opa(scr->image_324, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_324, 24, 117);

    // Init scr->label_682
    scr->label_682 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_682, "烹饪时间");
    lv_label_set_long_mode(scr->label_682, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_682, 578, 139);
    lv_obj_set_size(scr->label_682, 125, 32);

    // Set style of scr->label_682
    lv_obj_set_style_text_font(scr->label_682, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_682, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 482, 248);
    lv_obj_set_size(scr->hour, 84, 72);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_684
    scr->label_684 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_684, "时");
    lv_label_set_long_mode(scr->label_684, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_684, 562, 280);
    lv_obj_set_size(scr->label_684, 38, 32);

    // Set style of scr->label_684
    lv_obj_set_style_text_font(scr->label_684, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_684, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_685
    scr->label_685 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_685, "分");
    lv_label_set_long_mode(scr->label_685, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_685, 762, 280);
    lv_obj_set_size(scr->label_685, 38, 32);

    // Set style of scr->label_685
    lv_obj_set_style_text_font(scr->label_685, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_685, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "30");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 682, 248);
    lv_obj_set_size(scr->min, 84, 72);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_687
    scr->label_687 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_687, "果馅卷");
    lv_label_set_long_mode(scr->label_687, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_687, 24, 25);
    lv_obj_set_size(scr->label_687, 144, 32);

    // Set style of scr->label_687
    lv_obj_set_style_text_font(scr->label_687, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_687, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_688
    scr->label_688 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_688, "下一步");
    lv_label_set_long_mode(scr->label_688, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_688, 996, 39);
    lv_obj_set_size(scr->label_688, 117, 32);

    // Set style of scr->label_688
    lv_obj_set_style_text_font(scr->label_688, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_688, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->obj);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 480, 327);
    lv_obj_add_flag(scr->hourline, LV_OBJ_FLAG_HIDDEN);

    // Init scr->minline
    scr->minline = lv_img_create(scr->obj);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 680, 327);
    lv_obj_add_flag(scr->minline, LV_OBJ_FLAG_HIDDEN);


}


