/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void textpage_create(ui_manager_t *ui)
{
    textpage_t *scr = textpage_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->font24
    scr->font24 = lv_label_create(scr->obj);
    lv_label_set_text(scr->font24, "℃一三上下中主义二五今保入六冷冻出分到功加包千单却卷发四回外多天奇始完定对小层已干年底开式强慢成披拔探插放日时明星曲月期材条果步殊段气洁流清温炸烤烧热烹煮特玉空米约能自色节菜萨薯西解请部酵针钟集面页顶预额风食饪馅骤！该不支持，持烘焙设、置、关、全、简、体、文快速全麦面包土司可颂麦颂配卷条网容把按展\n↑↓℃全麦面包土司可颂瑞士卷果馅卷玛德琳海绵蛋糕纸杯蛋糕巧克力蛋糕泡芙蛋挞千层酥曲奇饼干松饼\n麦颂瑞玛琳芙挞千酥曲奇饼松面糊模具糖粉酥皮冰奶油蛋奶冻汤匙厘米抹油涂倒压填撒冷却均匀\n℃↑↓个了八刷右后器大它左接方无来每液满然照状白直移脂至让调铺长℃↑↓、。一三个中串主义之五人以任份体你使便保温停入全六内冷冻分删到刷刺前加工务动助匀包千单卡卷去叉发吗否启味和喜喷器回土在均增备外多奇奶好始子孜完定将小尼层已布带干并底度开式当您意感慢成扎打披抹据掉排撒放效料时明暂有朝束条果架根椒次欢段气没油浅浆浇海深温炸烤烧烫烹然照熟牛肉物猪玉现用白的皮皿盐盘砂确碎种程第等箱米类粗红结缓网罗羊美肉肠胡胸脊脯腿色花草菜萨蒜蔬薄薯行表要计说请调谱豆还进部配酪酵里量钟铺锅门问题间防阶零需面页顶须预额食饪香骨高鱼鲜鳕鸡鸭黑！，：×—…→⏎七丢两于亮仅从他件传位低住侧信值做充其再准凉几击切制刻剂勿区午即厂原参取叠口号各名向含命哪团困地址块型垢域培声处复夜太失夹字存安寸少尖屏屑属己常平序应延形待微心态恢息悬想或所扇手才报拌择指换控提摆擦收数新是显普更替最服未本机杂板标栈框档榄橄欧止水汽波注消湿源演潮灭灯炉点焗熱燥父片版率球理生电界留盖相知矩破示禁秒立童签箔管繁组经继续编缘翅肪腔芹英茄菌萄葡蒸蓉藏虾蚝装裹褐覆言警认语误贝超转轻载辅辑边达过迎运返迟选透途通都酒酱释重金铝锁锡键闭附降除霜青静音預颜馨體鱿＋？");
    lv_label_set_long_mode(scr->font24, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->font24, 40, 34);
    lv_obj_set_size(scr->font24, 142, 32);

    // Set style of scr->font24
    lv_obj_set_style_text_font(scr->font24, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->font24, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->font24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->font30
    scr->font30 = lv_label_create(scr->obj);
    lv_label_set_text(scr->font30, "℃一三上下中主义二五今保入六冷冻出分到功加包千单却卷发四回外多天奇始完定对小层已干年底开式强慢成披拔探插放日时明星曲月期材条果步殊段气洁流清温炸烤烧热烹煮特玉空米约能自色节菜萨薯西解请部酵针钟集面页顶预额风食饪馅骤！该不支持，持烘焙没吗、增、要、还、问、需全麦面包土司可颂麦颂配卷条网容把按展\n↑↓℃全麦面包土司可颂瑞士卷果馅卷玛德琳海绵蛋糕纸杯蛋糕巧克力蛋糕泡芙蛋挞千层酥曲奇饼干松饼\n麦颂瑞玛琳芙挞千酥曲奇饼松面糊模具糖粉酥皮冰奶油蛋奶冻汤匙厘米抹油涂倒压填撒冷却均匀\n℃↑↓个了八刷右后器大它左接方无来每液满然照状白直移脂至让调铺长肪℃↑↓、。一三个中串主义之五人以任份体你使便保温停入全六内冷冻分删到刷刺前加工务动助匀包千单卡卷去叉发吗否启味和喜喷器回土在均增备外多奇奶好始子孜完定将小尼层已布带干并底度开式当您意感慢成扎打披抹据掉排撒放效料时明暂有朝束条果架根椒次欢段气没油浅浆浇海深温炸烤烧烫烹然照熟牛肉物猪玉现用白的皮皿盐盘砂确碎种程第等箱米类粗红结缓网罗羊美肉肠胡胸脊脯腿色花草菜萨蒜蔬薄薯行表要计说请调谱豆还进部配酪酵里量钟铺锅门问题间防阶零需面页顶须预额食饪香骨高鱼鲜鳕鸡鸭黑！，：°×—…℃↑→↓⏎、。一七三上下不丢两个中串主义之了二于五亮人仅今从他以件任份传位低住体你使侧便保信倒值做停充克入全八六关其具内再冰冷冻准凉几出击分切删到制刷刺刻剂前力功加务动助勿匀包匙区千午单卡即却卷厂压厘原去参叉发取叠口可右号司各名后向吗否含启味命和哪喜喷器四回团困土在地址均块型垢域培塔填增士声处备复外多夜大天太失夹奇奶好始子字存孜它安完定家容寸对将小少尖尼层屏屑展属工左巧己已布带常干平年并序应底度延开式强当形待微德心快态恢息您悬想意感慢成或所扇手才扎打把报披抹拌拔择持指按挞换据掉排探接控提插摆撒擦支收放效数文料新方无日时明星是显普暂曲更替最月有服朝期未本机杂材束条来杯松板果架标栈根框档椒榄模橄次欢欧止步殊段每气水汤汽没油泡波注洁流浅浆浇海涂消液深清温湿源满演潮灭灯炉炸点烘烤烧烫热烹焗焙然照煮熟熱燥父片版牛物特状猪率玉玛现球理琳瑞生用电界留白的皮皿盐盖盘直相知矩砂破确碎示禁禽种秒移程空立童第等签简箔管箱米类粉粗糊糕糖繁红约纸组经结继续绵缓编缘网罗置羊美翅肉肠肪胡胸能脂脊脯腔腿自至色节芙花芹英茄草菌菜萄萨葡蒜蒸蓉蔬薄薯藏虾蚝蛋行表装裹褐西要覆解言警计认让设该语误说请调谱豆贝超转轻载辅辑边达过迎运返还进迟选透途通速部都配酒酥酪酱酵释里重量金针钟铝铺锁锅锡键长门闭问间防阶附降除集零需霜青静面音預页顶须颂预题颜额风食饪饼馅香馨骤骨體高鱼鱿鲜鳕鸡鸭麦黑！＋，：？");
    lv_label_set_long_mode(scr->font30, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->font30, 203, 34);
    lv_obj_set_size(scr->font30, 142, 32);

    // Set style of scr->font30
    lv_obj_set_style_text_font(scr->font30, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->font30, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->font30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->font36
    scr->font36 = lv_label_create(scr->obj);
    lv_label_set_text(scr->font36, "℃一三上下中主义二五今保入六冷冻出分到功加包千单却卷发四回外多天奇始完定对小层已干年底开式强慢成披拔探插放日时明星曲月期材条果步殊段气洁流清温炸烤烧热烹煮特玉空米约能自色节菜萨薯西解请部酵针钟集面页顶预额风食饪馅骤！该不支持，持烘焙要、需全麦面包土司可颂麦颂配卷条网容把按展\n↑↓℃全麦面包土司可颂瑞士卷果馅卷玛德琳海绵蛋糕纸杯蛋糕巧克力蛋糕泡芙蛋挞千层酥曲奇饼干松饼\n麦颂瑞玛琳芙挞千酥曲奇饼松面糊模具糖粉酥皮冰奶油蛋奶冻汤匙厘米抹油涂倒压填撒冷却均匀\n℃↑↓个了八刷右后器大它左接方无来每液满然照状白直移脂至让调铺长根°×—…℃↑→↓⏎、。一七三上下不丢两个中串主义之了二于五亮人仅今从他以件任份传位低住体你使侧便保信倒值做停充克入全八六关其具内再冰冷冻准凉几出击分切删到制刷刺刻剂前力功加务动助勿匀包匙区千午单卡即却卷厂压厘原去参叉发取叠口可右号司各名后向吗否含启味命和哪喜喷器四回团困土在地址均块型垢域培塔填增士声处备复外多夜大天太失夹奇奶好始子字存孜它安完定家容寸对将小少尖尼层屏屑展属工左巧己已布带常干平年并序应底度延开式强当形待微德心快态恢息您悬想意感慢成或所扇手才扎打把报披抹拌拔择持指按挞换据掉排探接控提插摆撒擦支收放效数文料新方无日时明星是显普暂曲更替最月有服朝期未本机杂材束条来杯松板果架标栈根框档椒榄模橄次欢欧止步殊段每气水汤汽没油泡波注洁流浅浆浇海涂消液深清温湿源满演潮灭灯炉炸点烘烤烧烫热烹焗焙然照煮熟熱燥父片版牛物特状猪率玉玛现球理琳瑞生用电界留白的皮皿盐盖盘直相知矩砂破确碎示禁禽种秒移程空立童第等签简箔管箱米类粉粗糊糕糖繁红约纸组经结继续绵缓编缘网罗置羊美翅肉肠肪胡胸能脂脊脯腔腿自至色节芙花芹英茄草菌菜萄萨葡蒜蒸蓉蔬薄薯藏虾蚝蛋行表装裹褐西要覆解言警计认让设该语误说请调谱豆贝超转轻载辅辑边达过迎运返还进迟选透途通速部都配酒酥酪酱酵释里重量金针钟铝铺锁锅锡键长门闭问间防阶附降除集零需霜青静面音預页顶须颂预题颜额风食饪饼馅香馨骤骨體高鱼鱿鲜鳕鸡鸭麦黑！＋，：？");
    lv_label_set_long_mode(scr->font36, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->font36, 358, 34);
    lv_obj_set_size(scr->font36, 142, 32);

    // Set style of scr->font36
    lv_obj_set_style_text_font(scr->font36, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->font36, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->font36, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->font48
    scr->font48 = lv_label_create(scr->obj);
    lv_label_set_text(scr->font48, "℃一三上下中主义二五今保入六冷冻出分到功加包千单却卷发四回外多天奇始完定对小层已干年底开式强慢成披拔探插放日时明星曲月期材条果步殊段气洁流清温炸烤烧热烹煮特玉空米约能自色节菜萨薯西解请部酵针钟集面页顶预额风食饪馅骤！该不支持，持烘焙全麦面包土司可颂麦颂配卷条网容把按展\n↑↓℃全麦面包土司可颂瑞士卷果馅卷玛德琳海绵蛋糕纸杯蛋糕巧克力蛋糕泡芙蛋挞千层酥曲奇饼干松饼\n麦颂瑞玛琳芙挞千酥曲奇饼松面糊模具糖粉酥皮冰奶油蛋奶冻汤匙厘米抹油涂倒压填撒冷却均匀\n℃↑↓个了八刷右后器大它左接方无来每液满然照状白直移脂至让调铺长°×—…℃↑→↓⏎、。一七三上下不丢两个中串主义之了二于五亮人仅今从他以件任份传位低住体你使侧便保信倒值做停充克入全八六关其具内再冰冷冻准凉几出击分切删到制刷刺刻剂前力功加务动助勿匀包匙区千午单卡即却卷厂压厘原去参叉发取叠口可右号司各名后向吗否含启味命和哪喜喷器四回团困土在地址均块型垢域培塔填增士声处备复外多夜大天太失夹奇奶好始子字存孜它安完定家容寸对将小少尖尼层屏屑展属工左巧己已布带常干平年并序应底度延开式强当形待微德心快态恢息您悬想意感慢成或所扇手才扎打把报披抹拌拔择持指按挞换据掉排探接控提插摆撒擦支收放效数文料新方无日时明星是显普暂曲更替最月有服朝期未本机杂材束条来杯松板果架标栈根框档椒榄模橄次欢欧止步殊段每气水汤汽没油泡波注洁流浅浆浇海涂消液深清温湿源满演潮灭灯炉炸点烘烤烧烫热烹焗焙然照煮熟熱燥父片版牛物特状猪率玉玛现球理琳瑞生用电界留白的皮皿盐盖盘直相知矩砂破确碎示禁禽种秒移程空立童第等签简箔管箱米类粉粗糊糕糖繁红约纸组经结继续绵缓编缘网罗置羊美翅肉肠肪胡胸能脂脊脯腔腿自至色节芙花芹英茄草菌菜萄萨葡蒜蒸蓉蔬薄薯藏虾蚝蛋行表装裹褐西要覆解言警计认让设该语误说请调谱豆贝超转轻载辅辑边达过迎运返还进迟选透途通速部都配酒酥酪酱酵释里重量金针钟铝铺锁锅锡键长门闭问间防阶附降除集零需霜青静面音預页顶须颂预题颜额风食饪饼馅香馨骤骨體高鱼鱿鲜鳕鸡鸭麦黑！＋，：？");
    lv_label_set_long_mode(scr->font48, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->font48, 505, 34);
    lv_obj_set_size(scr->font48, 142, 32);

    // Set style of scr->font48
    lv_obj_set_style_text_font(scr->font48, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->font48, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->font48, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->font60
    scr->font60 = lv_label_create(scr->obj);
    lv_label_set_text(scr->font60, "℃一三上下中主义二五今保入六冷冻出分到功加包千单却卷发四回外多天奇始完定对小层已干年底开式强慢成披拔探插放日时明星曲月期材条果步殊段气洁流清温炸烤烧热烹煮特玉空米约能自色节菜萨薯西解请部酵针钟集面页顶预额风食饪馅骤！该不支持，持烘焙全麦面包土司可颂麦颂配卷条网容把按展\n↑↓℃全麦面包土司可颂瑞士卷果馅卷玛德琳海绵蛋糕纸杯蛋糕巧克力蛋糕泡芙蛋挞千层酥曲奇饼干松饼\n麦颂瑞玛琳芙挞千酥曲奇饼松面糊模具糖粉酥皮冰奶油蛋奶冻汤匙厘米抹油涂倒压填撒冷却均匀\n℃↑↓个了八刷右后器大它左接方无来每液满然照状白直移脂至让调铺长°×—…℃↑→↓⏎、。一七三上下不丢两个中串主义之了二于五亮人仅今从他以件任份传位低住体你使侧便保信倒值做停充克入全八六关其具内再冰冷冻准凉几出击分切删到制刷刺刻剂前力功加务动助勿匀包匙区千午单卡即却卷厂压厘原去参叉发取叠口可右号司各名后向吗否含启味命和哪喜喷器四回团困土在地址均块型垢域培塔填增士声处备复外多夜大天太失夹奇奶好始子字存孜它安完定家容寸对将小少尖尼层屏屑展属工左巧己已布带常干平年并序应底度延开式强当形待微德心快态恢息您悬想意感慢成或所扇手才扎打把报披抹拌拔择持指按挞换据掉排探接控提插摆撒擦支收放效数文料新方无日时明星是显普暂曲更替最月有服朝期未本机杂材束条来杯松板果架标栈根框档椒榄模橄次欢欧止步殊段每气水汤汽没油泡波注洁流浅浆浇海涂消液深清温湿源满演潮灭灯炉炸点烘烤烧烫热烹焗焙然照煮熟熱燥父片版牛物特状猪率玉玛现球理琳瑞生用电界留白的皮皿盐盖盘直相知矩砂破确碎示禁禽种秒移程空立童第等签简箔管箱米类粉粗糊糕糖繁红约纸组经结继续绵缓编缘网罗置羊美翅肉肠肪胡胸能脂脊脯腔腿自至色节芙花芹英茄草菌菜萄萨葡蒜蒸蓉蔬薄薯藏虾蚝蛋行表装裹褐西要覆解言警计认让设该语误说请调谱豆贝超转轻载辅辑边达过迎运返还进迟选透途通速部都配酒酥酪酱酵释里重量金针钟铝铺锁锅锡键长门闭问间防阶附降除集零需霜青静面音預页顶须颂预题颜额风食饪饼馅香馨骤骨體高鱼鱿鲜鳕鸡鸭麦黑！＋，：？");
    lv_label_set_long_mode(scr->font60, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->font60, 704, 37);
    lv_obj_set_size(scr->font60, 142, 32);

    // Set style of scr->font60
    lv_obj_set_style_text_font(scr->font60, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->font60, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->font60, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "24↑↓°");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 41, 173);
    lv_obj_set_size(scr->label_1, 142, 32);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, &c_aktivgroteskmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, "30↑↓°");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 208, 173);
    lv_obj_set_size(scr->label_2, 142, 32);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, &c_aktivgroteskmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_5, "36↑↓°");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 363, 173);
    lv_obj_set_size(scr->label_5, 142, 32);

    // Set style of scr->label_5
    lv_obj_set_style_text_font(scr->label_5, &c_aktivgroteskmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_6, "48↑↓°");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 517, 171);
    lv_obj_set_size(scr->label_6, 170, 32);

    // Set style of scr->label_6
    lv_obj_set_style_text_font(scr->label_6, &c_aktivgroteskmedium_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "60↑↓°");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 702, 173);
    lv_obj_set_size(scr->label_7, 142, 149);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, &c_aktivgroteskmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_8, "72↑↓°");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 846, 173);
    lv_obj_set_size(scr->label_8, 142, 250);

    // Set style of scr->label_8
    lv_obj_set_style_text_font(scr->label_8, &c_aktivgroteskmedium_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_9, "128↑↓°");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 79, 270);
    lv_obj_set_size(scr->label_9, 173, 121);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, &c_aktivgroteskmedium_128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "128↑↓°");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 347, 301);
    lv_obj_set_size(scr->label_3, 173, 121);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, &c_aktivgroteskmedium_125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


