/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void toastcolor_create(ui_manager_t *ui)
{
    toastcolor_t *scr = toastcolor_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(div1bg.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_style_img_opa(scr->image_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_9, 24, 119);

    // Init scr->label_23
    scr->label_23 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_23, "选择烤色程度");
    lv_label_set_long_mode(scr->label_23, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_23, 529, 139);
    lv_obj_set_size(scr->label_23, 216, 36);

    // Set style of scr->label_23
    lv_obj_set_style_text_font(scr->label_23, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_23, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_23, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_24
    scr->label_24 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_24, "面包卷");
    lv_label_set_long_mode(scr->label_24, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_24, 24, 24);
    lv_obj_set_size(scr->label_24, 144, 32);

    // Set style of scr->label_24
    lv_obj_set_style_text_font(scr->label_24, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_24, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "下一步");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 983, 22);
    lv_obj_set_size(scr->next, 135, 71);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->degree
    scr->degree = lv_label_create(scr->obj);
    lv_label_set_text(scr->degree, "浅中深");
    lv_label_set_long_mode(scr->degree, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->degree, 590, 248);
    lv_obj_set_size(scr->degree, 100, 77);

    // Set style of scr->degree
    lv_obj_set_style_text_font(scr->degree, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->degree, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->degree, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line
    scr->line = lv_img_create(scr->obj);
    lv_img_set_src(scr->line, LVGL_IMAGE_PATH(settingline3_73x4.png));
    lv_img_set_pivot(scr->line, 50, 50);
    lv_img_set_angle(scr->line, 0);
    lv_obj_set_style_img_opa(scr->line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->line, 606, 328);

    // Init scr->weight
    scr->weight = lv_label_create(scr->obj);
    lv_label_set_text(scr->weight, "1600");
    lv_label_set_long_mode(scr->weight, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->weight, 519, 248);
    lv_obj_set_size(scr->weight, 167, 77);

    // Set style of scr->weight
    lv_obj_set_style_text_font(scr->weight, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->weight, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->weight, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->weighticon
    scr->weighticon = lv_label_create(scr->obj);
    lv_label_set_text(scr->weighticon, "g");
    lv_label_set_long_mode(scr->weighticon, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->weighticon, 685, 280);
    lv_obj_set_size(scr->weighticon, 21, 42);

    // Set style of scr->weighticon
    lv_obj_set_style_text_font(scr->weighticon, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->weighticon, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->weighticon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->weightline3
    scr->weightline3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->weightline3, LVGL_IMAGE_PATH(settingline3_141x4.png));
    lv_img_set_pivot(scr->weightline3, 50, 50);
    lv_img_set_angle(scr->weightline3, 0);
    lv_obj_set_style_img_opa(scr->weightline3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->weightline3, 569, 328);

    // Init scr->weightline4
    scr->weightline4 = lv_img_create(scr->obj);
    lv_img_set_src(scr->weightline4, LVGL_IMAGE_PATH(settingline3_179x4.png));
    lv_img_set_pivot(scr->weightline4, 50, 50);
    lv_img_set_angle(scr->weightline4, 0);
    lv_obj_set_style_img_opa(scr->weightline4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->weightline4, 530, 328);

    // Init scr->Maturity
    scr->Maturity = lv_label_create(scr->obj);
    lv_label_set_text(scr->Maturity, "全熟");
    lv_label_set_long_mode(scr->Maturity, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->Maturity, 531, 248);
    lv_obj_set_size(scr->Maturity, 218, 77);

    // Set style of scr->Maturity
    lv_obj_set_style_text_font(scr->Maturity, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->Maturity, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->Maturity, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->maturityline3
    scr->maturityline3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->maturityline3, LVGL_IMAGE_PATH(settingline3_211x4.png));
    lv_img_set_pivot(scr->maturityline3, 50, 50);
    lv_img_set_angle(scr->maturityline3, 0);
    lv_obj_set_style_img_opa(scr->maturityline3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->maturityline3, 537, 328);

    // Init scr->maturityline2
    scr->maturityline2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->maturityline2, LVGL_IMAGE_PATH(settingline3_139x4.png));
    lv_img_set_pivot(scr->maturityline2, 50, 50);
    lv_img_set_angle(scr->maturityline2, 0);
    lv_obj_set_style_img_opa(scr->maturityline2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->maturityline2, 572, 328);


}


