/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void top_bbq_setting_create(ui_manager_t *ui)
{
    top_bbq_setting_t *scr = top_bbq_setting_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label
    scr->time_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->time_label, "00:19:59");
    lv_label_set_long_mode(scr->time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label, 907, 157);
    lv_obj_set_size(scr->time_label, 235, 60);

    // Set style of scr->time_label
    lv_obj_set_style_text_font(scr->time_label, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_4
    scr->container_4 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_4, 0, 0);
    lv_obj_set_size(scr->container_4, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_4, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_4
    lv_obj_set_style_bg_color(scr->container_4, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_4, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_38
    scr->image_38 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_38, LVGL_IMAGE_PATH(settingbk.png));
    lv_img_set_pivot(scr->image_38, 50, 50);
    lv_img_set_angle(scr->image_38, 0);
    lv_obj_set_style_img_opa(scr->image_38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_38, 115, 115);

    // Init scr->label_83
    scr->label_83 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_83, "温度");
    lv_label_set_long_mode(scr->label_83, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_83, 242, 136);
    lv_obj_set_size(scr->label_83, 73, 30);

    // Set style of scr->label_83
    lv_obj_set_style_text_font(scr->label_83, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_83, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_83, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_84
    scr->label_84 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_84, "烹饪时间");
    lv_label_set_long_mode(scr->label_84, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_84, 454, 136);
    lv_obj_set_size(scr->label_84, 135, 30);

    // Set style of scr->label_84
    lv_obj_set_style_text_font(scr->label_84, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_84, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_84, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 213, 213);
    lv_obj_set_size(scr->temp, 102, 46);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon3
    scr->icon3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon3, "℃");
    lv_label_set_long_mode(scr->icon3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon3, 300, 229);
    lv_obj_set_size(scr->icon3, 37, 30);

    // Set style of scr->icon3
    lv_obj_set_style_text_font(scr->icon3, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line2
    scr->line2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->line2, LVGL_IMAGE_PATH(settingline3_87x4.png));
    lv_img_set_pivot(scr->line2, 50, 50);
    lv_img_set_angle(scr->line2, 0);
    lv_obj_set_style_img_opa(scr->line2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->line2, 236, 269);

    // Init scr->line3
    scr->line3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->line3, LVGL_IMAGE_PATH(settingline2.png));
    lv_img_set_pivot(scr->line3, 50, 50);
    lv_img_set_angle(scr->line3, 0);
    lv_obj_set_style_img_opa(scr->line3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->line3, 223, 269);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 374, 213);
    lv_obj_set_size(scr->hour, 102, 46);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "00");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 537, 213);
    lv_obj_set_size(scr->min, 102, 46);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->min, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_93
    scr->label_93 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_93, "时");
    lv_label_set_long_mode(scr->label_93, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_93, 449, 229);
    lv_obj_set_size(scr->label_93, 37, 30);

    // Set style of scr->label_93
    lv_obj_set_style_text_font(scr->label_93, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_93, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_93, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_94
    scr->label_94 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_94, "分");
    lv_label_set_long_mode(scr->label_94, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_94, 612, 229);
    lv_obj_set_size(scr->label_94, 37, 30);

    // Set style of scr->label_94
    lv_obj_set_style_text_font(scr->label_94, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_94, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_94, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->obj);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 398, 269);

    // Init scr->minline
    scr->minline = lv_img_create(scr->obj);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(settingline3.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 560, 269);

    // Init scr->icon2
    scr->icon2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon2, "℃");
    lv_label_set_long_mode(scr->icon2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon2, 288, 229);
    lv_obj_set_size(scr->icon2, 37, 30);

    // Set style of scr->icon2
    lv_obj_set_style_text_font(scr->icon2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->surebutton
    scr->surebutton = lv_btn_create(scr->obj);
    lv_obj_t *surebutton_label = lv_label_create(scr->surebutton);
    lv_label_set_text(surebutton_label, "确 认");
    lv_obj_align(surebutton_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->surebutton, 959, 295);
    lv_obj_set_size(scr->surebutton, 129, 83);

    // Set style of scr->surebutton
    lv_obj_set_style_bg_opa(scr->surebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->surebutton, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->surebutton, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->surebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->surebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->surebutton, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->surebutton, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


