/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void topflagpage_create(ui_manager_t *ui)
{
    topflagpage_t *scr = topflagpage_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

// Init scr->obj (hand-modified: created on lv_layer_top instead of a screen,
    // so it stays on top of all pages; remove theme card style to avoid border/padding.
    // NOTE: remove_style_all must run BEFORE set_size, because size is a style in LVGL9)
    scr->obj = lv_obj_create(lv_layer_top());
    lv_obj_remove_style_all(scr->obj);
    lv_obj_set_size(scr->obj, LV_HOR_RES, LV_VER_RES);
    lv_obj_remove_flag(scr->obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_remove_flag(scr->obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->currenttime
    scr->currenttime = lv_label_create(scr->obj);
    lv_label_set_text(scr->currenttime, "12:00");
    lv_label_set_long_mode(scr->currenttime, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->currenttime, 1196, 25);
    lv_obj_set_size(scr->currenttime, 60, 22);

    // Set style of scr->currenttime
    lv_obj_set_style_text_font(scr->currenttime, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->currenttime, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->currenttime, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->demo
    scr->demo = lv_img_create(scr->obj);
    lv_img_set_src(scr->demo, LVGL_IMAGE_PATH(show.png));
    lv_img_set_pivot(scr->demo, 50, 50);
    lv_img_set_angle(scr->demo, 0);
    lv_obj_set_style_img_opa(scr->demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->demo, 542, 24);

    // Init scr->timer
    scr->timer = lv_img_create(scr->obj);
    lv_img_set_src(scr->timer, LVGL_IMAGE_PATH(timer.png));
    lv_img_set_pivot(scr->timer, 50, 50);
    lv_img_set_angle(scr->timer, 0);
    lv_obj_set_style_img_opa(scr->timer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->timer, 627, 24);

    // Init scr->light
    scr->light = lv_img_create(scr->obj);
    lv_img_set_src(scr->light, LVGL_IMAGE_PATH(light.png));
    lv_img_set_pivot(scr->light, 50, 50);
    lv_img_set_angle(scr->light, 0);
    lv_obj_set_style_img_opa(scr->light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->light, 678, 24);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 0, 0);
    lv_obj_set_size(scr->container_1, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->container_1
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(lockifr.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 390, 119);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(childlock.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 453, 143);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->locktip1
    scr->locktip1 = lv_label_create(scr->container_1);
    lv_label_set_text(scr->locktip1, "已锁定");
    lv_label_set_long_mode(scr->locktip1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->locktip1, 458, 170);
    lv_obj_set_size(scr->locktip1, 370, 36);
    lv_obj_add_flag(scr->locktip1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->locktip1
    lv_obj_set_style_text_font(scr->locktip1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->locktip1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->locktip1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->locktip2
    scr->locktip2 = lv_label_create(scr->container_1);
    lv_label_set_text(scr->locktip2, "长按旋钮3秒进行解锁");
    lv_label_set_long_mode(scr->locktip2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->locktip2, 528, 211);
    lv_obj_set_size(scr->locktip2, 370, 36);
    lv_obj_add_flag(scr->locktip2, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->locktip2
    lv_obj_set_style_text_font(scr->locktip2, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->locktip2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->locktip2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->locktip3
    scr->locktip3 = lv_label_create(scr->container_1);
    lv_label_set_text(scr->locktip3, "上下烧烤烹饪中");
    lv_label_set_long_mode(scr->locktip3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->locktip3, 455, 297);
    lv_obj_set_size(scr->locktip3, 370, 36);
    lv_obj_add_flag(scr->locktip3, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->locktip3
    lv_obj_set_style_text_font(scr->locktip3, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->locktip3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->locktip3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tip1
    scr->tip1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->tip1, "烤箱运行时不可用。");
    lv_label_set_long_mode(scr->tip1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->tip1, 797, 161);
    lv_obj_set_size(scr->tip1, 450, 36);
    lv_obj_add_flag(scr->tip1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->tip1
    lv_obj_set_style_text_font(scr->tip1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->tip1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->tip1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tip2
    scr->tip2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->tip2, "请删除不太喜欢的烹调！");
    lv_label_set_long_mode(scr->tip2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->tip2, 836, 198);
    lv_obj_set_size(scr->tip2, 370, 36);
    lv_obj_add_flag(scr->tip2, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->tip2
    lv_obj_set_style_text_font(scr->tip2, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->tip2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->tip2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tip3
    scr->tip3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->tip3, "收藏成功");
    lv_label_set_long_mode(scr->tip3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->tip3, 838, 161);
    lv_obj_set_size(scr->tip3, 370, 61);
    lv_obj_add_flag(scr->tip3, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->tip3
    lv_obj_set_style_text_font(scr->tip3, &c_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->tip3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->tip3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure
    scr->sure = lv_btn_create(scr->obj);
    lv_obj_t *sure_label = lv_label_create(scr->sure);
    lv_label_set_text(sure_label, "确 定");
    lv_obj_align(sure_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure, 959, 295);
    lv_obj_set_size(scr->sure, 129, 83);
    lv_obj_add_flag(scr->sure, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->sure
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->sure, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->sure, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


