/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void topflagpage_create(ui_manager_t *ui)
{
    topflagpage_t *scr = topflagpage_get(ui);

    // NOTE: 本页面仅由 nav_init 调用一次（对象挂在 lv_layer_top 上，不会被屏幕加载回收）。
    // auto_del=true 时下方守卫不生效——请勿二次调用本函数，否则顶层对象会泄漏。
    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj (hand-modified: created on lv_layer_top instead of a screen,
    // so it stays on top of all pages; remove theme card style to avoid border/padding.
    // NOTE: remove_style_all must run BEFORE set_size, because size is a style in LVGL9)
    scr->obj = lv_obj_create(lv_layer_top());
    lv_obj_remove_style_all(scr->obj);
    lv_obj_set_size(scr->obj, LV_HOR_RES, LV_VER_RES);
    lv_obj_remove_flag(scr->obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_remove_flag(scr->obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->currenttime
    scr->currenttime = lv_label_create(scr->obj);
    lv_label_set_text(scr->currenttime, "12:00");
    lv_label_set_long_mode(scr->currenttime, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->currenttime, 1196, 25);
    lv_obj_set_size(scr->currenttime, 60, 22);

    // Set style of scr->currenttime
    lv_obj_set_style_text_font(scr->currenttime, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->currenttime, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->currenttime, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->demo
    scr->demo = lv_img_create(scr->obj);
    lv_img_set_src(scr->demo, LVGL_IMAGE_PATH(show.png));
    lv_img_set_pivot(scr->demo, 50, 50);
    lv_img_set_angle(scr->demo, 0);
    lv_obj_set_style_img_opa(scr->demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->demo, 542, 24);

    // Init scr->timer
    scr->timer = lv_img_create(scr->obj);
    lv_img_set_src(scr->timer, LVGL_IMAGE_PATH(timer.png));
    lv_img_set_pivot(scr->timer, 50, 50);
    lv_img_set_angle(scr->timer, 0);
    lv_obj_set_style_img_opa(scr->timer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->timer, 627, 24);

    // Init scr->light
    scr->light = lv_img_create(scr->obj);
    lv_img_set_src(scr->light, LVGL_IMAGE_PATH(light.png));
    lv_img_set_pivot(scr->light, 50, 50);
    lv_img_set_angle(scr->light, 0);
    lv_obj_set_style_img_opa(scr->light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->light, 678, 24);

    // Init scr->container_1 (同步自上机位:功能键无效提示遮罩,默认隐藏)
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 0, 0);
    lv_obj_set_size(scr->container_1, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->container_1
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 113, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->tip1 (文字"烤箱运行时不可用。"默认隐藏)
    scr->tip1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->tip1, "烤箱运行时不可用。");
    lv_label_set_long_mode(scr->tip1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->tip1, 885, 161);
    lv_obj_set_size(scr->tip1, 275, 36);
    lv_obj_add_flag(scr->tip1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->tip1
    lv_obj_set_style_text_font(scr->tip1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->tip1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->tip1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

}


