/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;


void ui_init(void)
{

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    waitmenu_24_create(&ui_manager);
    lv_scr_load(waitmenu_24_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
