/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void unfrozen_menu_create(ui_manager_t *ui)
{
    unfrozen_menu_t *scr = unfrozen_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->image_198
    scr->image_198 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_198, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_198, 50, 50);
    lv_img_set_angle(scr->image_198, 0);
    lv_obj_set_style_img_opa(scr->image_198, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_198, 24, 118);

    // Init scr->image_199
    scr->image_199 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_199, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_199, 50, 50);
    lv_img_set_angle(scr->image_199, 0);
    lv_obj_set_style_img_opa(scr->image_199, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_199, 645, 118);

    // Init scr->label_436
    scr->label_436 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_436, "温度");
    lv_label_set_long_mode(scr->label_436, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_436, 300, 137);
    lv_obj_set_size(scr->label_436, 64, 32);

    // Set style of scr->label_436
    lv_obj_set_style_text_font(scr->label_436, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_436, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "40");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 252, 249);
    lv_obj_set_size(scr->temp, 120, 72);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_438
    scr->label_438 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_438, "℃");
    lv_label_set_long_mode(scr->label_438, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_438, 372, 281);
    lv_obj_set_size(scr->label_438, 38, 32);

    // Set style of scr->label_438
    lv_obj_set_style_text_font(scr->label_438, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_438, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_439
    scr->label_439 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_439, "烹饪时间");
    lv_label_set_long_mode(scr->label_439, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_439, 891, 137);
    lv_obj_set_size(scr->label_439, 125, 32);

    // Set style of scr->label_439
    lv_obj_set_style_text_font(scr->label_439, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_439, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hour
    scr->hour = lv_label_create(scr->obj);
    lv_label_set_text(scr->hour, "00");
    lv_label_set_long_mode(scr->hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->hour, 793, 248);
    lv_obj_set_size(scr->hour, 84, 72);

    // Set style of scr->hour
    lv_obj_set_style_text_font(scr->hour, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_441
    scr->label_441 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_441, "时");
    lv_label_set_long_mode(scr->label_441, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_441, 872, 280);
    lv_obj_set_size(scr->label_441, 38, 32);

    // Set style of scr->label_441
    lv_obj_set_style_text_font(scr->label_441, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_441, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_442
    scr->label_442 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_442, "分");
    lv_label_set_long_mode(scr->label_442, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_442, 1075, 281);
    lv_obj_set_size(scr->label_442, 38, 32);

    // Set style of scr->label_442
    lv_obj_set_style_text_font(scr->label_442, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_442, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->min
    scr->min = lv_label_create(scr->obj);
    lv_label_set_text(scr->min, "30");
    lv_label_set_long_mode(scr->min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->min, 995, 248);
    lv_obj_set_size(scr->min, 84, 72);

    // Set style of scr->min
    lv_obj_set_style_text_font(scr->min, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_444
    scr->label_444 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_444, "解冻");
    lv_label_set_long_mode(scr->label_444, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_444, 24, 24);
    lv_obj_set_size(scr->label_444, 144, 32);

    // Set style of scr->label_444
    lv_obj_set_style_text_font(scr->label_444, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_444, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_445
    scr->label_445 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_445, "下一步");
    lv_label_set_long_mode(scr->label_445, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_445, 996, 39);
    lv_obj_set_size(scr->label_445, 117, 32);

    // Set style of scr->label_445
    lv_obj_set_style_text_font(scr->label_445, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_445, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->templine3
    scr->templine3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine3, LVGL_IMAGE_PATH(underline.png));
    lv_img_set_pivot(scr->templine3, 50, 50);
    lv_img_set_angle(scr->templine3, 0);
    lv_obj_set_style_img_opa(scr->templine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine3, 252, 328);
    lv_obj_add_flag(scr->templine3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->templine2
    scr->templine2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->templine2, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->templine2, 50, 50);
    lv_img_set_angle(scr->templine2, 0);
    lv_obj_set_style_img_opa(scr->templine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->templine2, 289, 328);
    lv_obj_add_flag(scr->templine2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->hourline
    scr->hourline = lv_img_create(scr->obj);
    lv_img_set_src(scr->hourline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->hourline, 50, 50);
    lv_img_set_angle(scr->hourline, 0);
    lv_obj_set_style_img_opa(scr->hourline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->hourline, 790, 328);
    lv_obj_add_flag(scr->hourline, LV_OBJ_FLAG_HIDDEN);

    // Init scr->minline
    scr->minline = lv_img_create(scr->obj);
    lv_img_set_src(scr->minline, LVGL_IMAGE_PATH(underline_120x4.png));
    lv_img_set_pivot(scr->minline, 50, 50);
    lv_img_set_angle(scr->minline, 0);
    lv_obj_set_style_img_opa(scr->minline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->minline, 993, 328);
    lv_obj_add_flag(scr->minline, LV_OBJ_FLAG_HIDDEN);


}


