/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void updown_bbq_complete_probe_create(ui_manager_t *ui)
{
    updown_bbq_complete_probe_t *scr = updown_bbq_complete_probe_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_30
    scr->image_30 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_30, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_30, 50, 50);
    lv_img_set_angle(scr->image_30, 0);
    lv_obj_set_style_img_opa(scr->image_30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_30, 115, 320);

    // Init scr->label_74
    scr->label_74 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_74, "| 上下烧烤 | 180℃ | 80℃");
    lv_label_set_long_mode(scr->label_74, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_74, 274, 232);
    lv_obj_set_size(scr->label_74, 490, 39);

    // Set style of scr->label_74
    lv_obj_set_style_text_font(scr->label_74, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_74, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_4
    scr->bar_4 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_4, 0, 0);
    lv_bar_set_value(scr->bar_4, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_4, 122, 326);
    lv_obj_set_size(scr->bar_4, 637, 20);

    // Set style of scr->bar_4
    lv_obj_set_style_bg_color(scr->bar_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_4, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_31
    scr->image_31 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_31, LVGL_IMAGE_PATH(updown_img.png));
    lv_img_set_pivot(scr->image_31, 50, 50);
    lv_img_set_angle(scr->image_31, 0);
    lv_obj_set_style_img_opa(scr->image_31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_31, 115, 161);

    // Init scr->label_75
    scr->label_75 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_75, "已完成");
    lv_label_set_long_mode(scr->label_75, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_75, 273, 157);
    lv_obj_set_size(scr->label_75, 235, 60);

    // Set style of scr->label_75
    lv_obj_set_style_text_font(scr->label_75, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_75, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_76
    scr->label_76 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_76, "高温防烫");
    lv_label_set_long_mode(scr->label_76, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_76, 896, 161);
    lv_obj_set_size(scr->label_76, 252, 36);

    // Set style of scr->label_76
    lv_obj_set_style_text_font(scr->label_76, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_76, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_76, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_77
    scr->label_77 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_77, "请缓慢打开门体！");
    lv_label_set_long_mode(scr->label_77, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_77, 896, 197);
    lv_obj_set_size(scr->label_77, 252, 36);

    // Set style of scr->label_77
    lv_obj_set_style_text_font(scr->label_77, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_77, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_77, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


}


