/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void updown_bbq_set_create(ui_manager_t *ui)
{
    updown_bbq_set_t *scr = updown_bbq_set_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->updown_label
    scr->updown_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->updown_label, "上下烧烤");
    lv_label_set_long_mode(scr->updown_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->updown_label, 24, 25);
    lv_obj_set_size(scr->updown_label, 144, 32);

    // Set style of scr->updown_label
    lv_obj_set_style_text_font(scr->updown_label, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->updown_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->wen_label
    scr->wen_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->wen_label, "温");
    lv_label_set_long_mode(scr->wen_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->wen_label, 165, 155);
    lv_obj_set_size(scr->wen_label, 26, 32);

    // Set style of scr->wen_label
    lv_obj_set_style_text_font(scr->wen_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->wen_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->du_label
    scr->du_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->du_label, "度：");
    lv_label_set_long_mode(scr->du_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->du_label, 252, 155);
    lv_obj_set_size(scr->du_label, 64, 32);

    // Set style of scr->du_label
    lv_obj_set_style_text_font(scr->du_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->du_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->du_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cooktime_label
    scr->cooktime_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->cooktime_label, "烹饪时间：");
    lv_label_set_long_mode(scr->cooktime_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cooktime_label, 141, 270);
    lv_obj_set_size(scr->cooktime_label, 175, 32);

    // Set style of scr->cooktime_label
    lv_obj_set_style_text_font(scr->cooktime_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cooktime_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->cooktime_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temimg_1
    scr->temimg_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->temimg_1, LVGL_IMAGE_PATH(tembk.png));
    lv_img_set_pivot(scr->temimg_1, 50, 50);
    lv_img_set_angle(scr->temimg_1, 0);
    lv_obj_set_style_img_opa(scr->temimg_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->temimg_1, 316, 143);

    // Init scr->temimg_2
    scr->temimg_2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->temimg_2, LVGL_IMAGE_PATH(tembk.png));
    lv_img_set_pivot(scr->temimg_2, 50, 50);
    lv_img_set_angle(scr->temimg_2, 0);
    lv_obj_set_style_img_opa(scr->temimg_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->temimg_2, 484, 143);

    // Init scr->temp_num_label
    scr->temp_num_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_num_label, "100");
    lv_label_set_long_mode(scr->temp_num_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_num_label, 342, 143);
    lv_obj_set_size(scr->temp_num_label, 87, 53);

    // Set style of scr->temp_num_label
    lv_obj_set_style_text_font(scr->temp_num_label, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp_num_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp_num_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->dir_label
    scr->dir_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->dir_label, "↑");
    lv_label_set_long_mode(scr->dir_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->dir_label, 325, 159);
    lv_obj_set_size(scr->dir_label, 26, 32);

    // Set style of scr->dir_label
    lv_obj_set_style_text_font(scr->dir_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dir_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->dir_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->dir_label_2
    scr->dir_label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->dir_label_2, "↓");
    lv_label_set_long_mode(scr->dir_label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->dir_label_2, 510, 159);
    lv_obj_set_size(scr->dir_label_2, 26, 32);

    // Set style of scr->dir_label_2
    lv_obj_set_style_text_font(scr->dir_label_2, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dir_label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->dir_label_2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_num_label_2
    scr->temp_num_label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_num_label_2, "80");
    lv_label_set_long_mode(scr->temp_num_label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_num_label_2, 528, 143);
    lv_obj_set_size(scr->temp_num_label_2, 59, 53);

    // Set style of scr->temp_num_label_2
    lv_obj_set_style_text_font(scr->temp_num_label_2, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp_num_label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp_num_label_2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon_label_1_2
    scr->icon_label_1_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon_label_1_2, "℃");
    lv_label_set_long_mode(scr->icon_label_1_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon_label_1_2, 590, 159);
    lv_obj_set_size(scr->icon_label_1_2, 26, 28);

    // Set style of scr->icon_label_1_2
    lv_obj_set_style_text_font(scr->icon_label_1_2, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon_label_1_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon_label_1_2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->icon_label_1
    scr->icon_label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->icon_label_1, "℃");
    lv_label_set_long_mode(scr->icon_label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->icon_label_1, 432, 159);
    lv_obj_set_size(scr->icon_label_1, 26, 28);

    // Set style of scr->icon_label_1
    lv_obj_set_style_text_font(scr->icon_label_1, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->icon_label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->icon_label_1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label
    scr->time_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->time_label, "01");
    lv_label_set_long_mode(scr->time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label, 307, 254);
    lv_obj_set_size(scr->time_label, 62, 53);

    // Set style of scr->time_label
    lv_obj_set_style_text_font(scr->time_label, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->time_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label_2
    scr->time_label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->time_label_2, "20");
    lv_label_set_long_mode(scr->time_label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label_2, 395, 254);
    lv_obj_set_size(scr->time_label_2, 58, 53);

    // Set style of scr->time_label_2
    lv_obj_set_style_text_font(scr->time_label_2, fs_taiwanpearl_regular_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->time_label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->time_label_2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->shi_label
    scr->shi_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->shi_label, "时");
    lv_label_set_long_mode(scr->shi_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->shi_label, 368, 270);
    lv_obj_set_size(scr->shi_label, 30, 32);

    // Set style of scr->shi_label
    lv_obj_set_style_text_font(scr->shi_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->shi_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->shi_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->fen_label
    scr->fen_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->fen_label, "分钟");
    lv_label_set_long_mode(scr->fen_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->fen_label, 448, 269);
    lv_obj_set_size(scr->fen_label, 64, 32);

    // Set style of scr->fen_label
    lv_obj_set_style_text_font(scr->fen_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->fen_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->fen_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->timer_img
    scr->timer_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->timer_img, LVGL_IMAGE_PATH(timer.png));
    lv_img_set_pivot(scr->timer_img, 50, 50);
    lv_img_set_angle(scr->timer_img, 0);
    lv_obj_set_style_img_opa(scr->timer_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->timer_img, 627, 24);

    // Init scr->place_img
    scr->place_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->place_img, LVGL_IMAGE_PATH(place_1.png));
    lv_img_set_pivot(scr->place_img, 50, 50);
    lv_img_set_angle(scr->place_img, 0);
    lv_obj_set_style_img_opa(scr->place_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->place_img, 164, 376);

    // Init scr->place_label
    scr->place_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->place_label, "烤架位置 3");
    lv_label_set_long_mode(scr->place_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->place_label, 232, 385);
    lv_obj_set_size(scr->place_label, 148, 32);

    // Set style of scr->place_label
    lv_obj_set_style_text_font(scr->place_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->place_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->place_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->sure_button
    scr->sure_button = lv_btn_create(scr->obj);
    lv_obj_t *sure_button_label = lv_label_create(scr->sure_button);
    lv_label_set_text(sure_button_label, "确 定");
    lv_obj_align(sure_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->sure_button, 983, 22);
    lv_obj_set_size(scr->sure_button, 135, 71);

    // Set style of scr->sure_button
    lv_obj_set_style_bg_opa(scr->sure_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->sure_button, LVGL_IMAGE_PATH(surebk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->sure_button, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->sure_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->sure_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->righttime_label
    scr->righttime_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->righttime_label, "12:00");
    lv_label_set_long_mode(scr->righttime_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->righttime_label, 1197, 24);
    lv_obj_set_size(scr->righttime_label, 65, 32);

    // Set style of scr->righttime_label
    lv_obj_set_style_text_font(scr->righttime_label, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->righttime_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->preheat_label
    scr->preheat_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->preheat_label, "快速预热");
    lv_label_set_long_mode(scr->preheat_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->preheat_label, 830, 154);
    lv_obj_set_size(scr->preheat_label, 130, 32);

    // Set style of scr->preheat_label
    lv_obj_set_style_text_font(scr->preheat_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->preheat_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->preheat_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->yan_label
    scr->yan_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->yan_label, "延");
    lv_label_set_long_mode(scr->yan_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->yan_label, 840, 270);
    lv_obj_set_size(scr->yan_label, 26, 32);

    // Set style of scr->yan_label
    lv_obj_set_style_text_font(scr->yan_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->yan_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chi_label
    scr->chi_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->chi_label, "迟");
    lv_label_set_long_mode(scr->chi_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->chi_label, 930, 270);
    lv_obj_set_size(scr->chi_label, 26, 32);

    // Set style of scr->chi_label
    lv_obj_set_style_text_font(scr->chi_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->chi_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contain_label
    scr->contain_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->contain_label, "自动保温");
    lv_label_set_long_mode(scr->contain_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->contain_label, 831, 381);
    lv_obj_set_size(scr->contain_label, 130, 32);

    // Set style of scr->contain_label
    lv_obj_set_style_text_font(scr->contain_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->contain_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->contain_label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_3
    scr->button_3 = lv_btn_create(scr->obj);
    lv_obj_t *button_3_label = lv_label_create(scr->button_3);
    lv_label_set_text(button_3_label, "");
    lv_obj_align(button_3_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_3, 986, 144);
    lv_obj_set_size(scr->button_3, 129, 53);

    // Set style of scr->button_3
    lv_obj_set_style_bg_opa(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_3, LVGL_IMAGE_PATH(on1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_4
    scr->button_4 = lv_btn_create(scr->obj);
    lv_obj_t *button_4_label = lv_label_create(scr->button_4);
    lv_label_set_text(button_4_label, "");
    lv_obj_align(button_4_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_4, 986, 260);
    lv_obj_set_size(scr->button_4, 129, 53);

    // Set style of scr->button_4
    lv_obj_set_style_bg_opa(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_4, LVGL_IMAGE_PATH(off.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_4, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_5
    scr->button_5 = lv_btn_create(scr->obj);
    lv_obj_t *button_5_label = lv_label_create(scr->button_5);
    lv_label_set_text(button_5_label, "");
    lv_obj_align(button_5_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_5, 986, 373);
    lv_obj_set_size(scr->button_5, 129, 53);

    // Set style of scr->button_5
    lv_obj_set_style_bg_opa(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_5, LVGL_IMAGE_PATH(on2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_5, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}


