/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void updown_bbq_menu_create(ui_manager_t *ui)
{
    updown_bbq_menu_t *scr = updown_bbq_menu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->next_button
    scr->next_button = lv_btn_create(scr->obj);
    lv_obj_t *next_button_label = lv_label_create(scr->next_button);
    lv_label_set_text(next_button_label, "");
    lv_obj_align(next_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next_button, 981, 22);
    lv_obj_set_size(scr->next_button, 138, 70);

    // Set style of scr->next_button
    lv_obj_set_style_bg_opa(scr->next_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next_button, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next_button, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 24, 118);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(div2bk.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 645, 118);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "温度");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 300, 137);
    lv_obj_set_size(scr->label_1, 64, 32);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, "180");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 252, 249);
    lv_obj_set_size(scr->label_2, 120, 72);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, fs_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "℃");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 372, 281);
    lv_obj_set_size(scr->label_3, 38, 32);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_4, "烹饪时间");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 891, 137);
    lv_obj_set_size(scr->label_4, 125, 32);

    // Set style of scr->label_4
    lv_obj_set_style_text_font(scr->label_4, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_5, "01");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 793, 248);
    lv_obj_set_size(scr->label_5, 84, 72);

    // Set style of scr->label_5
    lv_obj_set_style_text_font(scr->label_5, fs_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_6, "时");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 872, 280);
    lv_obj_set_size(scr->label_6, 38, 32);

    // Set style of scr->label_6
    lv_obj_set_style_text_font(scr->label_6, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "分");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 1075, 281);
    lv_obj_set_size(scr->label_7, 38, 32);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_8, "20");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 995, 248);
    lv_obj_set_size(scr->label_8, 84, 72);

    // Set style of scr->label_8
    lv_obj_set_style_text_font(scr->label_8, fs_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_9, "上下烧烤");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 24, 25);
    lv_obj_set_size(scr->label_9, 144, 32);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_12, "下一步");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 996, 39);
    lv_obj_set_size(scr->label_12, 117, 32);

    // Set style of scr->label_12
    lv_obj_set_style_text_font(scr->label_12, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_10, "12:00");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 1179, 24);
    lv_obj_set_size(scr->label_10, 77, 32);

    // Set style of scr->label_10
    lv_obj_set_style_text_font(scr->label_10, fs_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);


}


