/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void updown_bbq_cooking_create(ui_manager_t *ui)
{
    updown_bbq_cooking_t *scr = updown_bbq_cooking_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->updown_label
    scr->updown_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->updown_label, "| 上下烧烤 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->updown_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->updown_label, 274, 232);
    lv_obj_set_size(scr->updown_label, 490, 39);

    // Set style of scr->updown_label
    lv_obj_set_style_text_font(scr->updown_label, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->updown_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->time_label
    scr->time_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->time_label, "00:19:59");
    lv_label_set_long_mode(scr->time_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->time_label, 907, 157);
    lv_obj_set_size(scr->time_label, 235, 60);

    // Set style of scr->time_label
    lv_obj_set_style_text_font(scr->time_label, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->time_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->stop_button
    scr->stop_button = lv_btn_create(scr->obj);
    lv_obj_t *stop_button_label = lv_label_create(scr->stop_button);
    lv_label_set_text(stop_button_label, "暂 停");
    lv_obj_align(stop_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->stop_button, 959, 295);
    lv_obj_set_size(scr->stop_button, 129, 83);

    // Set style of scr->stop_button
    lv_obj_set_style_bg_opa(scr->stop_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->stop_button, LVGL_IMAGE_PATH(stopbk1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->stop_button, fs_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->stop_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->stop_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->stop_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->stop_button, LVGL_IMAGE_PATH(stopbk2.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->barbk_img
    scr->barbk_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->barbk_img, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->barbk_img, 50, 50);
    lv_img_set_angle(scr->barbk_img, 0);
    lv_obj_set_style_img_opa(scr->barbk_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->barbk_img, 115, 320);

    // Init scr->bar
    scr->bar = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar, 0, 0);
    lv_bar_set_value(scr->bar, 2, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar, 122, 326);
    lv_obj_set_size(scr->bar, 637, 20);

    // Set style of scr->bar
    lv_obj_set_style_bg_color(scr->bar, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->updown_img
    scr->updown_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->updown_img, LVGL_IMAGE_PATH(updown_img.png));
    lv_img_set_pivot(scr->updown_img, 50, 50);
    lv_img_set_angle(scr->updown_img, 0);
    lv_obj_set_style_img_opa(scr->updown_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->updown_img, 115, 161);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_10, "烹饪中...");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 273, 157);
    lv_obj_set_size(scr->label_10, 235, 60);

    // Set style of scr->label_10
    lv_obj_set_style_text_font(scr->label_10, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->little_button
    scr->little_button = lv_btn_create(scr->obj);
    lv_obj_t *little_button_label = lv_label_create(scr->little_button);
    lv_label_set_text(little_button_label, "");
    lv_obj_align(little_button_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->little_button, 609, 170);
    lv_obj_set_size(scr->little_button, 50, 43);

    // Set style of scr->little_button
    lv_obj_set_style_bg_opa(scr->little_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->little_button, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->little_button, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->little_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->little_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->little_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->little_button, LVGL_IMAGE_PATH(little100.png), LV_PART_MAIN | LV_STATE_FOCUSED);


}


