/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void updown_bbq_menu_low_create(ui_manager_t *ui)
{
    updown_bbq_menu_low_t *scr = updown_bbq_menu_low_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_30
    scr->image_30 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_30, LVGL_IMAGE_PATH(preheatbg.png));
    lv_img_set_pivot(scr->image_30, 50, 50);
    lv_img_set_angle(scr->image_30, 0);
    lv_obj_set_style_img_opa(scr->image_30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_30, 24, 118);

    // Init scr->next
    scr->next = lv_btn_create(scr->obj);
    lv_obj_t *next_label = lv_label_create(scr->next);
    lv_label_set_text(next_label, "");
    lv_obj_align(next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->next, 981, 22);
    lv_obj_set_size(scr->next, 138, 70);

    // Set style of scr->next
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextbk.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->next, &c_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->next, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->next, LVGL_IMAGE_PATH(nextstep_bk.png), LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_57
    scr->label_57 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_57, "下一步");
    lv_label_set_long_mode(scr->label_57, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_57, 996, 39);
    lv_obj_set_size(scr->label_57, 108, 32);

    // Set style of scr->label_57
    lv_obj_set_style_text_font(scr->label_57, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_57, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_57, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_60
    scr->label_60 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_60, "上下烧烤");
    lv_label_set_long_mode(scr->label_60, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_60, 24, 24);
    lv_obj_set_size(scr->label_60, 144, 32);

    // Set style of scr->label_60
    lv_obj_set_style_text_font(scr->label_60, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_60, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "温度");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 608, 139);
    lv_obj_set_size(scr->label_7, 60, 32);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp
    scr->temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp, "180");
    lv_label_set_long_mode(scr->temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp, 562, 248);
    lv_obj_set_size(scr->temp, 120, 72);

    // Set style of scr->temp
    lv_obj_set_style_text_font(scr->temp, &c_taiwanpearl_regular_72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->temp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_9, "℃");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 682, 280);
    lv_obj_set_size(scr->label_9, 38, 32);

    // Set style of scr->label_9
    lv_obj_set_style_text_font(scr->label_9, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->dir2
    scr->dir2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->dir2, "↓");
    lv_label_set_long_mode(scr->dir2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->dir2, 570, 280);
    lv_obj_set_size(scr->dir2, 31, 41);

    // Set style of scr->dir2
    lv_obj_set_style_text_font(scr->dir2, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dir2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->dir2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->dir2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->dir3
    scr->dir3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->dir3, "↓");
    lv_label_set_long_mode(scr->dir3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->dir3, 531, 280);
    lv_obj_set_size(scr->dir3, 31, 41);

    // Set style of scr->dir3
    lv_obj_set_style_text_font(scr->dir3, &c_taiwanpearl_regular_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dir3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->dir3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->dir3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line3
    scr->line3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->line3, LVGL_IMAGE_PATH(underline_181x4.png));
    lv_img_set_pivot(scr->line3, 50, 50);
    lv_img_set_angle(scr->line3, 0);
    lv_obj_set_style_img_opa(scr->line3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->line3, 538, 327);
    lv_obj_add_flag(scr->line3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->line2
    scr->line2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->line2, LVGL_IMAGE_PATH(underline_146x4.png));
    lv_img_set_pivot(scr->line2, 50, 50);
    lv_img_set_angle(scr->line2, 0);
    lv_obj_set_style_img_opa(scr->line2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->line2, 573, 327);
    lv_obj_add_flag(scr->line2, LV_OBJ_FLAG_HIDDEN);


}


