/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void vegetablemenu_create(ui_manager_t *ui)
{
    vegetablemenu_t *scr = vegetablemenu_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bt1
    scr->bt1 = lv_btn_create(scr->obj);
    lv_obj_t *bt1_label = lv_label_create(scr->bt1);
    lv_label_set_text(bt1_label, "烤土豆片");
    lv_obj_align(bt1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->bt1, 18, 76);
    lv_obj_set_size(scr->bt1, 313, 386);

    // Set style of scr->bt1
    lv_obj_set_style_bg_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->bt1, LVGL_IMAGE_PATH(div7_1_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->bt1, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->bt1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->bt1, LVGL_IMAGE_PATH(div7_1_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->bt1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->button_11
    scr->button_11 = lv_btn_create(scr->obj);
    lv_obj_t *button_11_label = lv_label_create(scr->button_11);
    lv_label_set_text(button_11_label, "烤茄子");
    lv_obj_align(button_11_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_11, 330, 76);
    lv_obj_set_size(scr->button_11, 310, 193);

    // Set style of scr->button_11
    lv_obj_set_style_bg_opa(scr->button_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_11, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_11, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_11, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "蔬菜");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 24, 24);
    lv_obj_set_size(scr->label_7, 97, 25);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, &c_taiwanpearl_regular_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_15
    scr->button_15 = lv_btn_create(scr->obj);
    lv_obj_t *button_15_label = lv_label_create(scr->button_15);
    lv_label_set_text(button_15_label, "烤玉米");
    lv_obj_align(button_15_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_15, 640, 76);
    lv_obj_set_size(scr->button_15, 310, 193);

    // Set style of scr->button_15
    lv_obj_set_style_bg_opa(scr->button_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_15, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_15, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_15, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->button_16
    scr->button_16 = lv_btn_create(scr->obj);
    lv_obj_t *button_16_label = lv_label_create(scr->button_16);
    lv_label_set_text(button_16_label, "烤杂蔬");
    lv_obj_align(button_16_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_16, 950, 76);
    lv_obj_set_size(scr->button_16, 310, 193);

    // Set style of scr->button_16
    lv_obj_set_style_bg_opa(scr->button_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_16, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_16, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_16, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->button_17
    scr->button_17 = lv_btn_create(scr->obj);
    lv_obj_t *button_17_label = lv_label_create(scr->button_17);
    lv_label_set_text(button_17_label, "烤带皮土豆");
    lv_obj_align(button_17_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_17, 330, 269);
    lv_obj_set_size(scr->button_17, 310, 193);

    // Set style of scr->button_17
    lv_obj_set_style_bg_opa(scr->button_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_17, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_17, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_17, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_17, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_17, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_17, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->button_18
    scr->button_18 = lv_btn_create(scr->obj);
    lv_obj_t *button_18_label = lv_label_create(scr->button_18);
    lv_label_set_text(button_18_label, "奶油焗土豆");
    lv_obj_align(button_18_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_18, 640, 269);
    lv_obj_set_size(scr->button_18, 310, 193);

    // Set style of scr->button_18
    lv_obj_set_style_bg_opa(scr->button_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_18, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_18, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_18, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_18, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_18, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_18, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Init scr->button_19
    scr->button_19 = lv_btn_create(scr->obj);
    lv_obj_t *button_19_label = lv_label_create(scr->button_19);
    lv_label_set_text(button_19_label, "烤红薯");
    lv_obj_align(button_19_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_19, 950, 269);
    lv_obj_set_size(scr->button_19, 310, 193);

    // Set style of scr->button_19
    lv_obj_set_style_bg_opa(scr->button_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_19, LVGL_IMAGE_PATH(div7_2_30.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_19, &c_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_19, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(scr->button_19, LVGL_IMAGE_PATH(div7_2_80.png), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(scr->button_19, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(scr->button_19, 0, LV_PART_MAIN | LV_STATE_FOCUSED);


}


