/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void waterclean_complete_create(ui_manager_t *ui)
{
    waterclean_complete_t *scr = waterclean_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_style_img_opa(scr->image_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_9, 115, 320);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_12, "| 水解自清洁 | 10分钟 |");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 274, 232);
    lv_obj_set_size(scr->label_12, 490, 39);

    // Set style of scr->label_12
    lv_obj_set_style_text_font(scr->label_12, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_4
    scr->bar_4 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_4, 0, 0);
    lv_bar_set_value(scr->bar_4, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_4, 122, 326);
    lv_obj_set_size(scr->bar_4, 637, 20);

    // Set style of scr->bar_4
    lv_obj_set_style_bg_color(scr->bar_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_4, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_10
    scr->image_10 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_10, LVGL_IMAGE_PATH(watercleanicon.png));
    lv_img_set_pivot(scr->image_10, 50, 50);
    lv_img_set_angle(scr->image_10, 0);
    lv_obj_set_style_img_opa(scr->image_10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_10, 115, 161);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_13, "已完成");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 273, 157);
    lv_obj_set_size(scr->label_13, 235, 60);

    // Set style of scr->label_13
    lv_obj_set_style_text_font(scr->label_13, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_12
    scr->image_12 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_12, LVGL_IMAGE_PATH(tips.png));
    lv_img_set_pivot(scr->image_12, 50, 50);
    lv_img_set_angle(scr->image_12, 0);
    lv_obj_set_style_img_opa(scr->image_12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_12, 902, 160);


}


