/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void windchange_bbq_complete_create(ui_manager_t *ui)
{
    windchange_bbq_complete_t *scr = windchange_bbq_complete_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(bg.jpg), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_159
    scr->image_159 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_159, LVGL_IMAGE_PATH(bar.png));
    lv_img_set_pivot(scr->image_159, 50, 50);
    lv_img_set_angle(scr->image_159, 0);
    lv_obj_set_style_img_opa(scr->image_159, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_159, 115, 320);

    // Init scr->status
    scr->status = lv_label_create(scr->obj);
    lv_label_set_text(scr->status, "| 热风对流 | 180℃ | 1小时20分钟");
    lv_label_set_long_mode(scr->status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->status, 274, 232);
    lv_obj_set_size(scr->status, 490, 39);

    // Set style of scr->status
    lv_obj_set_style_text_font(scr->status, fs_taiwanpearl_regular_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->status, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_33
    scr->bar_33 = lv_bar_create(scr->obj);
    lv_obj_set_style_anim_time(scr->bar_33, 0, 0);
    lv_bar_set_value(scr->bar_33, 100, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_33, 122, 326);
    lv_obj_set_size(scr->bar_33, 637, 20);

    // Set style of scr->bar_33
    lv_obj_set_style_bg_color(scr->bar_33, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_33, lv_color_hex(0xffffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_356
    scr->label_356 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_356, "已完成");
    lv_label_set_long_mode(scr->label_356, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_356, 273, 157);
    lv_obj_set_size(scr->label_356, 235, 60);

    // Set style of scr->label_356
    lv_obj_set_style_text_font(scr->label_356, fs_taiwanpearl_regular_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_356, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_160
    scr->image_160 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_160, LVGL_IMAGE_PATH(hotcare.png));
    lv_img_set_pivot(scr->image_160, 50, 50);
    lv_img_set_angle(scr->image_160, 0);
    lv_obj_set_style_img_opa(scr->image_160, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_160, 845, 160);

    // Init scr->button_119
    scr->button_119 = lv_btn_create(scr->obj);
    lv_obj_t *button_119_label = lv_label_create(scr->button_119);
    lv_label_set_text(button_119_label, "");
    lv_obj_align(button_119_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_119, 609, 170);
    lv_obj_set_size(scr->button_119, 50, 43);

    // Set style of scr->button_119
    lv_obj_set_style_bg_opa(scr->button_119, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->button_119, LVGL_IMAGE_PATH(little.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_119, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_119, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_119, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_161
    scr->image_161 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_161, LVGL_IMAGE_PATH(windchange.png));
    lv_img_set_pivot(scr->image_161, 50, 50);
    lv_img_set_angle(scr->image_161, 0);
    lv_obj_set_style_img_opa(scr->image_161, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_161, 115, 161);


}


